
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * *
 *  * User
 *  * ├─ Aim
 *  * ├─ Tasks
 *  * ├─ Proofs
 *  * ├─ FocusSessions
 *  * relations -
 *  * 1 user -many tasks, many proofs
 *  * 1 task - multiple proofs
 *  * 1 proof type -many tasks related
 */
export type User = Prisma.UserModel
/**
 * Model Aim
 * 
 */
export type Aim = Prisma.AimModel
/**
 * Model Task
 * 
 */
export type Task = Prisma.TaskModel
/**
 * Model Proof
 * 
 */
export type Proof = Prisma.ProofModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model TaskActivityLog
 * 
 */
export type TaskActivityLog = Prisma.TaskActivityLogModel
/**
 * Model FocusSession
 * 
 */
export type FocusSession = Prisma.FocusSessionModel
/**
 * Model TaskSessions
 * 
 */
export type TaskSessions = Prisma.TaskSessionsModel
/**
 * Model BlockedApp
 * 
 */
export type BlockedApp = Prisma.BlockedAppModel
