
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AimStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED'
} as const

export type AimStatus = (typeof AimStatus)[keyof typeof AimStatus]


export const TaskStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  PROOF_PENDING: 'PROOF_PENDING',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]


export const VerificationStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const

export type VerificationStatus = (typeof VerificationStatus)[keyof typeof VerificationStatus]


export const FocusSessionStatus = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED'
} as const

export type FocusSessionStatus = (typeof FocusSessionStatus)[keyof typeof FocusSessionStatus]


export const VerifierType = {
  HUMAN: 'HUMAN',
  AI: 'AI',
  GITHUB: 'GITHUB',
  GMAIL: 'GMAIL',
  VIDEO_ANALYSIS: 'VIDEO_ANALYSIS'
} as const

export type VerifierType = (typeof VerifierType)[keyof typeof VerifierType]


export const Types = {
  GithubLink: 'GithubLink',
  DeployedLink: 'DeployedLink',
  Video: 'Video',
  Email: 'Email'
} as const

export type Types = (typeof Types)[keyof typeof Types]
