
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Aim: 'Aim',
  TaskType: 'TaskType',
  Task: 'Task',
  ProofType: 'ProofType',
  TaskTypeProofType: 'TaskTypeProofType',
  Proof: 'Proof',
  Verification: 'Verification',
  TaskActivityLog: 'TaskActivityLog',
  FocusSession: 'FocusSession',
  FocusSessionTask: 'FocusSessionTask',
  BlockedApp: 'BlockedApp'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AimScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  deadline: 'deadline',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
} as const

export type AimScalarFieldEnum = (typeof AimScalarFieldEnum)[keyof typeof AimScalarFieldEnum]


export const TaskTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type TaskTypeScalarFieldEnum = (typeof TaskTypeScalarFieldEnum)[keyof typeof TaskTypeScalarFieldEnum]


export const TaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  created_at: 'created_at',
  durationMins: 'durationMins',
  startTime: 'startTime',
  endTime: 'endTime',
  is_completed: 'is_completed',
  userId: 'userId',
  taskTypeId: 'taskTypeId',
  aimId: 'aimId'
} as const

export type TaskScalarFieldEnum = (typeof TaskScalarFieldEnum)[keyof typeof TaskScalarFieldEnum]


export const ProofTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type ProofTypeScalarFieldEnum = (typeof ProofTypeScalarFieldEnum)[keyof typeof ProofTypeScalarFieldEnum]


export const TaskTypeProofTypeScalarFieldEnum = {
  id: 'id',
  taskTypeId: 'taskTypeId',
  proofTypeId: 'proofTypeId'
} as const

export type TaskTypeProofTypeScalarFieldEnum = (typeof TaskTypeProofTypeScalarFieldEnum)[keyof typeof TaskTypeProofTypeScalarFieldEnum]


export const ProofScalarFieldEnum = {
  id: 'id',
  proofData: 'proofData',
  taskId: 'taskId',
  userId: 'userId',
  proofTypeId: 'proofTypeId'
} as const

export type ProofScalarFieldEnum = (typeof ProofScalarFieldEnum)[keyof typeof ProofScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  status: 'status',
  confidence: 'confidence',
  reason: 'reason',
  rawResponse: 'rawResponse',
  verifiedAt: 'verifiedAt',
  taskId: 'taskId',
  proofId: 'proofId'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const TaskActivityLogScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  action: 'action',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type TaskActivityLogScalarFieldEnum = (typeof TaskActivityLogScalarFieldEnum)[keyof typeof TaskActivityLogScalarFieldEnum]


export const FocusSessionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  startTime: 'startTime',
  endTime: 'endTime',
  status: 'status',
  createdAt: 'createdAt',
  userId: 'userId',
  taskId: 'taskId'
} as const

export type FocusSessionScalarFieldEnum = (typeof FocusSessionScalarFieldEnum)[keyof typeof FocusSessionScalarFieldEnum]


export const FocusSessionTaskScalarFieldEnum = {
  id: 'id',
  focusSessionId: 'focusSessionId',
  taskId: 'taskId',
  assignedAt: 'assignedAt'
} as const

export type FocusSessionTaskScalarFieldEnum = (typeof FocusSessionTaskScalarFieldEnum)[keyof typeof FocusSessionTaskScalarFieldEnum]


export const BlockedAppScalarFieldEnum = {
  id: 'id',
  appName: 'appName',
  packageName: 'packageName',
  focusSessionId: 'focusSessionId'
} as const

export type BlockedAppScalarFieldEnum = (typeof BlockedAppScalarFieldEnum)[keyof typeof BlockedAppScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

