
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Aim` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Aim
 * 
 */
export type AimModel = runtime.Types.Result.DefaultSelection<Prisma.$AimPayload>

export type AggregateAim = {
  _count: AimCountAggregateOutputType | null
  _min: AimMinAggregateOutputType | null
  _max: AimMaxAggregateOutputType | null
}

export type AimMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  status: $Enums.AimStatus | null
  deadline: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type AimMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  status: $Enums.AimStatus | null
  deadline: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type AimCountAggregateOutputType = {
  id: number
  title: number
  description: number
  status: number
  deadline: number
  createdAt: number
  updatedAt: number
  userId: number
  _all: number
}


export type AimMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  status?: true
  deadline?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type AimMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  status?: true
  deadline?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type AimCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  status?: true
  deadline?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  _all?: true
}

export type AimAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Aim to aggregate.
   */
  where?: Prisma.AimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aims to fetch.
   */
  orderBy?: Prisma.AimOrderByWithRelationInput | Prisma.AimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Aims
  **/
  _count?: true | AimCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AimMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AimMaxAggregateInputType
}

export type GetAimAggregateType<T extends AimAggregateArgs> = {
      [P in keyof T & keyof AggregateAim]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAim[P]>
    : Prisma.GetScalarType<T[P], AggregateAim[P]>
}




export type AimGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AimWhereInput
  orderBy?: Prisma.AimOrderByWithAggregationInput | Prisma.AimOrderByWithAggregationInput[]
  by: Prisma.AimScalarFieldEnum[] | Prisma.AimScalarFieldEnum
  having?: Prisma.AimScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AimCountAggregateInputType | true
  _min?: AimMinAggregateInputType
  _max?: AimMaxAggregateInputType
}

export type AimGroupByOutputType = {
  id: string
  title: string
  description: string
  status: $Enums.AimStatus
  deadline: Date | null
  createdAt: Date
  updatedAt: Date
  userId: string
  _count: AimCountAggregateOutputType | null
  _min: AimMinAggregateOutputType | null
  _max: AimMaxAggregateOutputType | null
}

export type GetAimGroupByPayload<T extends AimGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AimGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AimGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AimGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AimGroupByOutputType[P]>
      }
    >
  >



export type AimWhereInput = {
  AND?: Prisma.AimWhereInput | Prisma.AimWhereInput[]
  OR?: Prisma.AimWhereInput[]
  NOT?: Prisma.AimWhereInput | Prisma.AimWhereInput[]
  id?: Prisma.StringFilter<"Aim"> | string
  title?: Prisma.StringFilter<"Aim"> | string
  description?: Prisma.StringFilter<"Aim"> | string
  status?: Prisma.EnumAimStatusFilter<"Aim"> | $Enums.AimStatus
  deadline?: Prisma.DateTimeNullableFilter<"Aim"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Aim"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Aim"> | Date | string
  userId?: Prisma.StringFilter<"Aim"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  tasks?: Prisma.TaskListRelationFilter
}

export type AimOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  tasks?: Prisma.TaskOrderByRelationAggregateInput
}

export type AimWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AimWhereInput | Prisma.AimWhereInput[]
  OR?: Prisma.AimWhereInput[]
  NOT?: Prisma.AimWhereInput | Prisma.AimWhereInput[]
  title?: Prisma.StringFilter<"Aim"> | string
  description?: Prisma.StringFilter<"Aim"> | string
  status?: Prisma.EnumAimStatusFilter<"Aim"> | $Enums.AimStatus
  deadline?: Prisma.DateTimeNullableFilter<"Aim"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Aim"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Aim"> | Date | string
  userId?: Prisma.StringFilter<"Aim"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  tasks?: Prisma.TaskListRelationFilter
}, "id">

export type AimOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.AimCountOrderByAggregateInput
  _max?: Prisma.AimMaxOrderByAggregateInput
  _min?: Prisma.AimMinOrderByAggregateInput
}

export type AimScalarWhereWithAggregatesInput = {
  AND?: Prisma.AimScalarWhereWithAggregatesInput | Prisma.AimScalarWhereWithAggregatesInput[]
  OR?: Prisma.AimScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AimScalarWhereWithAggregatesInput | Prisma.AimScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Aim"> | string
  title?: Prisma.StringWithAggregatesFilter<"Aim"> | string
  description?: Prisma.StringWithAggregatesFilter<"Aim"> | string
  status?: Prisma.EnumAimStatusWithAggregatesFilter<"Aim"> | $Enums.AimStatus
  deadline?: Prisma.DateTimeNullableWithAggregatesFilter<"Aim"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Aim"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Aim"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"Aim"> | string
}

export type AimCreateInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAimsInput
  tasks?: Prisma.TaskCreateNestedManyWithoutAimInput
}

export type AimUncheckedCreateInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutAimInput
}

export type AimUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAimsNestedInput
  tasks?: Prisma.TaskUpdateManyWithoutAimNestedInput
}

export type AimUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutAimNestedInput
}

export type AimCreateManyInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
}

export type AimUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AimUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AimListRelationFilter = {
  every?: Prisma.AimWhereInput
  some?: Prisma.AimWhereInput
  none?: Prisma.AimWhereInput
}

export type AimOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AimCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AimMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AimMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AimNullableScalarRelationFilter = {
  is?: Prisma.AimWhereInput | null
  isNot?: Prisma.AimWhereInput | null
}

export type AimCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AimCreateWithoutUserInput, Prisma.AimUncheckedCreateWithoutUserInput> | Prisma.AimCreateWithoutUserInput[] | Prisma.AimUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AimCreateOrConnectWithoutUserInput | Prisma.AimCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AimCreateManyUserInputEnvelope
  connect?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
}

export type AimUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AimCreateWithoutUserInput, Prisma.AimUncheckedCreateWithoutUserInput> | Prisma.AimCreateWithoutUserInput[] | Prisma.AimUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AimCreateOrConnectWithoutUserInput | Prisma.AimCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AimCreateManyUserInputEnvelope
  connect?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
}

export type AimUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AimCreateWithoutUserInput, Prisma.AimUncheckedCreateWithoutUserInput> | Prisma.AimCreateWithoutUserInput[] | Prisma.AimUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AimCreateOrConnectWithoutUserInput | Prisma.AimCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AimUpsertWithWhereUniqueWithoutUserInput | Prisma.AimUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AimCreateManyUserInputEnvelope
  set?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  disconnect?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  delete?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  connect?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  update?: Prisma.AimUpdateWithWhereUniqueWithoutUserInput | Prisma.AimUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AimUpdateManyWithWhereWithoutUserInput | Prisma.AimUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AimScalarWhereInput | Prisma.AimScalarWhereInput[]
}

export type AimUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AimCreateWithoutUserInput, Prisma.AimUncheckedCreateWithoutUserInput> | Prisma.AimCreateWithoutUserInput[] | Prisma.AimUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AimCreateOrConnectWithoutUserInput | Prisma.AimCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AimUpsertWithWhereUniqueWithoutUserInput | Prisma.AimUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AimCreateManyUserInputEnvelope
  set?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  disconnect?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  delete?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  connect?: Prisma.AimWhereUniqueInput | Prisma.AimWhereUniqueInput[]
  update?: Prisma.AimUpdateWithWhereUniqueWithoutUserInput | Prisma.AimUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AimUpdateManyWithWhereWithoutUserInput | Prisma.AimUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AimScalarWhereInput | Prisma.AimScalarWhereInput[]
}

export type EnumAimStatusFieldUpdateOperationsInput = {
  set?: $Enums.AimStatus
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type AimCreateNestedOneWithoutTasksInput = {
  create?: Prisma.XOR<Prisma.AimCreateWithoutTasksInput, Prisma.AimUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.AimCreateOrConnectWithoutTasksInput
  connect?: Prisma.AimWhereUniqueInput
}

export type AimUpdateOneWithoutTasksNestedInput = {
  create?: Prisma.XOR<Prisma.AimCreateWithoutTasksInput, Prisma.AimUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.AimCreateOrConnectWithoutTasksInput
  upsert?: Prisma.AimUpsertWithoutTasksInput
  disconnect?: Prisma.AimWhereInput | boolean
  delete?: Prisma.AimWhereInput | boolean
  connect?: Prisma.AimWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AimUpdateToOneWithWhereWithoutTasksInput, Prisma.AimUpdateWithoutTasksInput>, Prisma.AimUncheckedUpdateWithoutTasksInput>
}

export type AimCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  tasks?: Prisma.TaskCreateNestedManyWithoutAimInput
}

export type AimUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  tasks?: Prisma.TaskUncheckedCreateNestedManyWithoutAimInput
}

export type AimCreateOrConnectWithoutUserInput = {
  where: Prisma.AimWhereUniqueInput
  create: Prisma.XOR<Prisma.AimCreateWithoutUserInput, Prisma.AimUncheckedCreateWithoutUserInput>
}

export type AimCreateManyUserInputEnvelope = {
  data: Prisma.AimCreateManyUserInput | Prisma.AimCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AimUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AimWhereUniqueInput
  update: Prisma.XOR<Prisma.AimUpdateWithoutUserInput, Prisma.AimUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AimCreateWithoutUserInput, Prisma.AimUncheckedCreateWithoutUserInput>
}

export type AimUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AimWhereUniqueInput
  data: Prisma.XOR<Prisma.AimUpdateWithoutUserInput, Prisma.AimUncheckedUpdateWithoutUserInput>
}

export type AimUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AimScalarWhereInput
  data: Prisma.XOR<Prisma.AimUpdateManyMutationInput, Prisma.AimUncheckedUpdateManyWithoutUserInput>
}

export type AimScalarWhereInput = {
  AND?: Prisma.AimScalarWhereInput | Prisma.AimScalarWhereInput[]
  OR?: Prisma.AimScalarWhereInput[]
  NOT?: Prisma.AimScalarWhereInput | Prisma.AimScalarWhereInput[]
  id?: Prisma.StringFilter<"Aim"> | string
  title?: Prisma.StringFilter<"Aim"> | string
  description?: Prisma.StringFilter<"Aim"> | string
  status?: Prisma.EnumAimStatusFilter<"Aim"> | $Enums.AimStatus
  deadline?: Prisma.DateTimeNullableFilter<"Aim"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Aim"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Aim"> | Date | string
  userId?: Prisma.StringFilter<"Aim"> | string
}

export type AimCreateWithoutTasksInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAimsInput
}

export type AimUncheckedCreateWithoutTasksInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
}

export type AimCreateOrConnectWithoutTasksInput = {
  where: Prisma.AimWhereUniqueInput
  create: Prisma.XOR<Prisma.AimCreateWithoutTasksInput, Prisma.AimUncheckedCreateWithoutTasksInput>
}

export type AimUpsertWithoutTasksInput = {
  update: Prisma.XOR<Prisma.AimUpdateWithoutTasksInput, Prisma.AimUncheckedUpdateWithoutTasksInput>
  create: Prisma.XOR<Prisma.AimCreateWithoutTasksInput, Prisma.AimUncheckedCreateWithoutTasksInput>
  where?: Prisma.AimWhereInput
}

export type AimUpdateToOneWithWhereWithoutTasksInput = {
  where?: Prisma.AimWhereInput
  data: Prisma.XOR<Prisma.AimUpdateWithoutTasksInput, Prisma.AimUncheckedUpdateWithoutTasksInput>
}

export type AimUpdateWithoutTasksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAimsNestedInput
}

export type AimUncheckedUpdateWithoutTasksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AimCreateManyUserInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.AimStatus
  deadline?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AimUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tasks?: Prisma.TaskUpdateManyWithoutAimNestedInput
}

export type AimUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tasks?: Prisma.TaskUncheckedUpdateManyWithoutAimNestedInput
}

export type AimUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumAimStatusFieldUpdateOperationsInput | $Enums.AimStatus
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AimCountOutputType
 */

export type AimCountOutputType = {
  tasks: number
}

export type AimCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tasks?: boolean | AimCountOutputTypeCountTasksArgs
}

/**
 * AimCountOutputType without action
 */
export type AimCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AimCountOutputType
   */
  select?: Prisma.AimCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AimCountOutputType without action
 */
export type AimCountOutputTypeCountTasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskWhereInput
}


export type AimSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  deadline?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  tasks?: boolean | Prisma.Aim$tasksArgs<ExtArgs>
  _count?: boolean | Prisma.AimCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aim"]>

export type AimSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  deadline?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aim"]>

export type AimSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  deadline?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aim"]>

export type AimSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  deadline?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
}

export type AimOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "status" | "deadline" | "createdAt" | "updatedAt" | "userId", ExtArgs["result"]["aim"]>
export type AimInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  tasks?: boolean | Prisma.Aim$tasksArgs<ExtArgs>
  _count?: boolean | Prisma.AimCountOutputTypeDefaultArgs<ExtArgs>
}
export type AimIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AimIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AimPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Aim"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    tasks: Prisma.$TaskPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string
    status: $Enums.AimStatus
    deadline: Date | null
    createdAt: Date
    updatedAt: Date
    userId: string
  }, ExtArgs["result"]["aim"]>
  composites: {}
}

export type AimGetPayload<S extends boolean | null | undefined | AimDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AimPayload, S>

export type AimCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AimFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AimCountAggregateInputType | true
  }

export interface AimDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Aim'], meta: { name: 'Aim' } }
  /**
   * Find zero or one Aim that matches the filter.
   * @param {AimFindUniqueArgs} args - Arguments to find a Aim
   * @example
   * // Get one Aim
   * const aim = await prisma.aim.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AimFindUniqueArgs>(args: Prisma.SelectSubset<T, AimFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Aim that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AimFindUniqueOrThrowArgs} args - Arguments to find a Aim
   * @example
   * // Get one Aim
   * const aim = await prisma.aim.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AimFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AimFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Aim that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AimFindFirstArgs} args - Arguments to find a Aim
   * @example
   * // Get one Aim
   * const aim = await prisma.aim.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AimFindFirstArgs>(args?: Prisma.SelectSubset<T, AimFindFirstArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Aim that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AimFindFirstOrThrowArgs} args - Arguments to find a Aim
   * @example
   * // Get one Aim
   * const aim = await prisma.aim.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AimFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AimFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Aims that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AimFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Aims
   * const aims = await prisma.aim.findMany()
   * 
   * // Get first 10 Aims
   * const aims = await prisma.aim.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const aimWithIdOnly = await prisma.aim.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AimFindManyArgs>(args?: Prisma.SelectSubset<T, AimFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Aim.
   * @param {AimCreateArgs} args - Arguments to create a Aim.
   * @example
   * // Create one Aim
   * const Aim = await prisma.aim.create({
   *   data: {
   *     // ... data to create a Aim
   *   }
   * })
   * 
   */
  create<T extends AimCreateArgs>(args: Prisma.SelectSubset<T, AimCreateArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Aims.
   * @param {AimCreateManyArgs} args - Arguments to create many Aims.
   * @example
   * // Create many Aims
   * const aim = await prisma.aim.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AimCreateManyArgs>(args?: Prisma.SelectSubset<T, AimCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Aims and returns the data saved in the database.
   * @param {AimCreateManyAndReturnArgs} args - Arguments to create many Aims.
   * @example
   * // Create many Aims
   * const aim = await prisma.aim.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Aims and only return the `id`
   * const aimWithIdOnly = await prisma.aim.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AimCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AimCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Aim.
   * @param {AimDeleteArgs} args - Arguments to delete one Aim.
   * @example
   * // Delete one Aim
   * const Aim = await prisma.aim.delete({
   *   where: {
   *     // ... filter to delete one Aim
   *   }
   * })
   * 
   */
  delete<T extends AimDeleteArgs>(args: Prisma.SelectSubset<T, AimDeleteArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Aim.
   * @param {AimUpdateArgs} args - Arguments to update one Aim.
   * @example
   * // Update one Aim
   * const aim = await prisma.aim.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AimUpdateArgs>(args: Prisma.SelectSubset<T, AimUpdateArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Aims.
   * @param {AimDeleteManyArgs} args - Arguments to filter Aims to delete.
   * @example
   * // Delete a few Aims
   * const { count } = await prisma.aim.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AimDeleteManyArgs>(args?: Prisma.SelectSubset<T, AimDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Aims.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AimUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Aims
   * const aim = await prisma.aim.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AimUpdateManyArgs>(args: Prisma.SelectSubset<T, AimUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Aims and returns the data updated in the database.
   * @param {AimUpdateManyAndReturnArgs} args - Arguments to update many Aims.
   * @example
   * // Update many Aims
   * const aim = await prisma.aim.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Aims and only return the `id`
   * const aimWithIdOnly = await prisma.aim.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AimUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AimUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Aim.
   * @param {AimUpsertArgs} args - Arguments to update or create a Aim.
   * @example
   * // Update or create a Aim
   * const aim = await prisma.aim.upsert({
   *   create: {
   *     // ... data to create a Aim
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Aim we want to update
   *   }
   * })
   */
  upsert<T extends AimUpsertArgs>(args: Prisma.SelectSubset<T, AimUpsertArgs<ExtArgs>>): Prisma.Prisma__AimClient<runtime.Types.Result.GetResult<Prisma.$AimPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Aims.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AimCountArgs} args - Arguments to filter Aims to count.
   * @example
   * // Count the number of Aims
   * const count = await prisma.aim.count({
   *   where: {
   *     // ... the filter for the Aims we want to count
   *   }
   * })
  **/
  count<T extends AimCountArgs>(
    args?: Prisma.Subset<T, AimCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AimCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Aim.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AimAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AimAggregateArgs>(args: Prisma.Subset<T, AimAggregateArgs>): Prisma.PrismaPromise<GetAimAggregateType<T>>

  /**
   * Group by Aim.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AimGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AimGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AimGroupByArgs['orderBy'] }
      : { orderBy?: AimGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AimGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAimGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Aim model
 */
readonly fields: AimFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Aim.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AimClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tasks<T extends Prisma.Aim$tasksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Aim$tasksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Aim model
 */
export interface AimFieldRefs {
  readonly id: Prisma.FieldRef<"Aim", 'String'>
  readonly title: Prisma.FieldRef<"Aim", 'String'>
  readonly description: Prisma.FieldRef<"Aim", 'String'>
  readonly status: Prisma.FieldRef<"Aim", 'AimStatus'>
  readonly deadline: Prisma.FieldRef<"Aim", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Aim", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Aim", 'DateTime'>
  readonly userId: Prisma.FieldRef<"Aim", 'String'>
}
    

// Custom InputTypes
/**
 * Aim findUnique
 */
export type AimFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * Filter, which Aim to fetch.
   */
  where: Prisma.AimWhereUniqueInput
}

/**
 * Aim findUniqueOrThrow
 */
export type AimFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * Filter, which Aim to fetch.
   */
  where: Prisma.AimWhereUniqueInput
}

/**
 * Aim findFirst
 */
export type AimFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * Filter, which Aim to fetch.
   */
  where?: Prisma.AimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aims to fetch.
   */
  orderBy?: Prisma.AimOrderByWithRelationInput | Prisma.AimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Aims.
   */
  cursor?: Prisma.AimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Aims.
   */
  distinct?: Prisma.AimScalarFieldEnum | Prisma.AimScalarFieldEnum[]
}

/**
 * Aim findFirstOrThrow
 */
export type AimFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * Filter, which Aim to fetch.
   */
  where?: Prisma.AimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aims to fetch.
   */
  orderBy?: Prisma.AimOrderByWithRelationInput | Prisma.AimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Aims.
   */
  cursor?: Prisma.AimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Aims.
   */
  distinct?: Prisma.AimScalarFieldEnum | Prisma.AimScalarFieldEnum[]
}

/**
 * Aim findMany
 */
export type AimFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * Filter, which Aims to fetch.
   */
  where?: Prisma.AimWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Aims to fetch.
   */
  orderBy?: Prisma.AimOrderByWithRelationInput | Prisma.AimOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Aims.
   */
  cursor?: Prisma.AimWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Aims from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Aims.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Aims.
   */
  distinct?: Prisma.AimScalarFieldEnum | Prisma.AimScalarFieldEnum[]
}

/**
 * Aim create
 */
export type AimCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * The data needed to create a Aim.
   */
  data: Prisma.XOR<Prisma.AimCreateInput, Prisma.AimUncheckedCreateInput>
}

/**
 * Aim createMany
 */
export type AimCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Aims.
   */
  data: Prisma.AimCreateManyInput | Prisma.AimCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Aim createManyAndReturn
 */
export type AimCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * The data used to create many Aims.
   */
  data: Prisma.AimCreateManyInput | Prisma.AimCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Aim update
 */
export type AimUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * The data needed to update a Aim.
   */
  data: Prisma.XOR<Prisma.AimUpdateInput, Prisma.AimUncheckedUpdateInput>
  /**
   * Choose, which Aim to update.
   */
  where: Prisma.AimWhereUniqueInput
}

/**
 * Aim updateMany
 */
export type AimUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Aims.
   */
  data: Prisma.XOR<Prisma.AimUpdateManyMutationInput, Prisma.AimUncheckedUpdateManyInput>
  /**
   * Filter which Aims to update
   */
  where?: Prisma.AimWhereInput
  /**
   * Limit how many Aims to update.
   */
  limit?: number
}

/**
 * Aim updateManyAndReturn
 */
export type AimUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * The data used to update Aims.
   */
  data: Prisma.XOR<Prisma.AimUpdateManyMutationInput, Prisma.AimUncheckedUpdateManyInput>
  /**
   * Filter which Aims to update
   */
  where?: Prisma.AimWhereInput
  /**
   * Limit how many Aims to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Aim upsert
 */
export type AimUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * The filter to search for the Aim to update in case it exists.
   */
  where: Prisma.AimWhereUniqueInput
  /**
   * In case the Aim found by the `where` argument doesn't exist, create a new Aim with this data.
   */
  create: Prisma.XOR<Prisma.AimCreateInput, Prisma.AimUncheckedCreateInput>
  /**
   * In case the Aim was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AimUpdateInput, Prisma.AimUncheckedUpdateInput>
}

/**
 * Aim delete
 */
export type AimDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
  /**
   * Filter which Aim to delete.
   */
  where: Prisma.AimWhereUniqueInput
}

/**
 * Aim deleteMany
 */
export type AimDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Aims to delete
   */
  where?: Prisma.AimWhereInput
  /**
   * Limit how many Aims to delete.
   */
  limit?: number
}

/**
 * Aim.tasks
 */
export type Aim$tasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  where?: Prisma.TaskWhereInput
  orderBy?: Prisma.TaskOrderByWithRelationInput | Prisma.TaskOrderByWithRelationInput[]
  cursor?: Prisma.TaskWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TaskScalarFieldEnum | Prisma.TaskScalarFieldEnum[]
}

/**
 * Aim without action
 */
export type AimDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Aim
   */
  select?: Prisma.AimSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Aim
   */
  omit?: Prisma.AimOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AimInclude<ExtArgs> | null
}
