
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FocusSessionTask` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FocusSessionTask
 * 
 */
export type FocusSessionTaskModel = runtime.Types.Result.DefaultSelection<Prisma.$FocusSessionTaskPayload>

export type AggregateFocusSessionTask = {
  _count: FocusSessionTaskCountAggregateOutputType | null
  _min: FocusSessionTaskMinAggregateOutputType | null
  _max: FocusSessionTaskMaxAggregateOutputType | null
}

export type FocusSessionTaskMinAggregateOutputType = {
  id: string | null
  focusSessionId: string | null
  taskId: string | null
  assignedAt: Date | null
}

export type FocusSessionTaskMaxAggregateOutputType = {
  id: string | null
  focusSessionId: string | null
  taskId: string | null
  assignedAt: Date | null
}

export type FocusSessionTaskCountAggregateOutputType = {
  id: number
  focusSessionId: number
  taskId: number
  assignedAt: number
  _all: number
}


export type FocusSessionTaskMinAggregateInputType = {
  id?: true
  focusSessionId?: true
  taskId?: true
  assignedAt?: true
}

export type FocusSessionTaskMaxAggregateInputType = {
  id?: true
  focusSessionId?: true
  taskId?: true
  assignedAt?: true
}

export type FocusSessionTaskCountAggregateInputType = {
  id?: true
  focusSessionId?: true
  taskId?: true
  assignedAt?: true
  _all?: true
}

export type FocusSessionTaskAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FocusSessionTask to aggregate.
   */
  where?: Prisma.FocusSessionTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessionTasks to fetch.
   */
  orderBy?: Prisma.FocusSessionTaskOrderByWithRelationInput | Prisma.FocusSessionTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FocusSessionTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessionTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessionTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FocusSessionTasks
  **/
  _count?: true | FocusSessionTaskCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FocusSessionTaskMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FocusSessionTaskMaxAggregateInputType
}

export type GetFocusSessionTaskAggregateType<T extends FocusSessionTaskAggregateArgs> = {
      [P in keyof T & keyof AggregateFocusSessionTask]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFocusSessionTask[P]>
    : Prisma.GetScalarType<T[P], AggregateFocusSessionTask[P]>
}




export type FocusSessionTaskGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FocusSessionTaskWhereInput
  orderBy?: Prisma.FocusSessionTaskOrderByWithAggregationInput | Prisma.FocusSessionTaskOrderByWithAggregationInput[]
  by: Prisma.FocusSessionTaskScalarFieldEnum[] | Prisma.FocusSessionTaskScalarFieldEnum
  having?: Prisma.FocusSessionTaskScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FocusSessionTaskCountAggregateInputType | true
  _min?: FocusSessionTaskMinAggregateInputType
  _max?: FocusSessionTaskMaxAggregateInputType
}

export type FocusSessionTaskGroupByOutputType = {
  id: string
  focusSessionId: string
  taskId: string
  assignedAt: Date
  _count: FocusSessionTaskCountAggregateOutputType | null
  _min: FocusSessionTaskMinAggregateOutputType | null
  _max: FocusSessionTaskMaxAggregateOutputType | null
}

export type GetFocusSessionTaskGroupByPayload<T extends FocusSessionTaskGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FocusSessionTaskGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FocusSessionTaskGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FocusSessionTaskGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FocusSessionTaskGroupByOutputType[P]>
      }
    >
  >



export type FocusSessionTaskWhereInput = {
  AND?: Prisma.FocusSessionTaskWhereInput | Prisma.FocusSessionTaskWhereInput[]
  OR?: Prisma.FocusSessionTaskWhereInput[]
  NOT?: Prisma.FocusSessionTaskWhereInput | Prisma.FocusSessionTaskWhereInput[]
  id?: Prisma.StringFilter<"FocusSessionTask"> | string
  focusSessionId?: Prisma.StringFilter<"FocusSessionTask"> | string
  taskId?: Prisma.StringFilter<"FocusSessionTask"> | string
  assignedAt?: Prisma.DateTimeFilter<"FocusSessionTask"> | Date | string
  focusSession?: Prisma.XOR<Prisma.FocusSessionScalarRelationFilter, Prisma.FocusSessionWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}

export type FocusSessionTaskOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  focusSession?: Prisma.FocusSessionOrderByWithRelationInput
  task?: Prisma.TaskOrderByWithRelationInput
}

export type FocusSessionTaskWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  focusSessionId_taskId?: Prisma.FocusSessionTaskFocusSessionIdTaskIdCompoundUniqueInput
  AND?: Prisma.FocusSessionTaskWhereInput | Prisma.FocusSessionTaskWhereInput[]
  OR?: Prisma.FocusSessionTaskWhereInput[]
  NOT?: Prisma.FocusSessionTaskWhereInput | Prisma.FocusSessionTaskWhereInput[]
  focusSessionId?: Prisma.StringFilter<"FocusSessionTask"> | string
  taskId?: Prisma.StringFilter<"FocusSessionTask"> | string
  assignedAt?: Prisma.DateTimeFilter<"FocusSessionTask"> | Date | string
  focusSession?: Prisma.XOR<Prisma.FocusSessionScalarRelationFilter, Prisma.FocusSessionWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}, "id" | "focusSessionId_taskId">

export type FocusSessionTaskOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  _count?: Prisma.FocusSessionTaskCountOrderByAggregateInput
  _max?: Prisma.FocusSessionTaskMaxOrderByAggregateInput
  _min?: Prisma.FocusSessionTaskMinOrderByAggregateInput
}

export type FocusSessionTaskScalarWhereWithAggregatesInput = {
  AND?: Prisma.FocusSessionTaskScalarWhereWithAggregatesInput | Prisma.FocusSessionTaskScalarWhereWithAggregatesInput[]
  OR?: Prisma.FocusSessionTaskScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FocusSessionTaskScalarWhereWithAggregatesInput | Prisma.FocusSessionTaskScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FocusSessionTask"> | string
  focusSessionId?: Prisma.StringWithAggregatesFilter<"FocusSessionTask"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"FocusSessionTask"> | string
  assignedAt?: Prisma.DateTimeWithAggregatesFilter<"FocusSessionTask"> | Date | string
}

export type FocusSessionTaskCreateInput = {
  id?: string
  assignedAt?: Date | string
  focusSession: Prisma.FocusSessionCreateNestedOneWithoutTasksInput
  task: Prisma.TaskCreateNestedOneWithoutFocusSessionTasksInput
}

export type FocusSessionTaskUncheckedCreateInput = {
  id?: string
  focusSessionId: string
  taskId: string
  assignedAt?: Date | string
}

export type FocusSessionTaskUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  focusSession?: Prisma.FocusSessionUpdateOneRequiredWithoutTasksNestedInput
  task?: Prisma.TaskUpdateOneRequiredWithoutFocusSessionTasksNestedInput
}

export type FocusSessionTaskUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionTaskCreateManyInput = {
  id?: string
  focusSessionId: string
  taskId: string
  assignedAt?: Date | string
}

export type FocusSessionTaskUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionTaskUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionTaskListRelationFilter = {
  every?: Prisma.FocusSessionTaskWhereInput
  some?: Prisma.FocusSessionTaskWhereInput
  none?: Prisma.FocusSessionTaskWhereInput
}

export type FocusSessionTaskOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FocusSessionTaskFocusSessionIdTaskIdCompoundUniqueInput = {
  focusSessionId: string
  taskId: string
}

export type FocusSessionTaskCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type FocusSessionTaskMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type FocusSessionTaskMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type FocusSessionTaskCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput> | Prisma.FocusSessionTaskCreateWithoutTaskInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput | Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyTaskInputEnvelope
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
}

export type FocusSessionTaskUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput> | Prisma.FocusSessionTaskCreateWithoutTaskInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput | Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyTaskInputEnvelope
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
}

export type FocusSessionTaskUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput> | Prisma.FocusSessionTaskCreateWithoutTaskInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput | Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutTaskInput | Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyTaskInputEnvelope
  set?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  disconnect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  delete?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  update?: Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutTaskInput | Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.FocusSessionTaskUpdateManyWithWhereWithoutTaskInput | Prisma.FocusSessionTaskUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.FocusSessionTaskScalarWhereInput | Prisma.FocusSessionTaskScalarWhereInput[]
}

export type FocusSessionTaskUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput> | Prisma.FocusSessionTaskCreateWithoutTaskInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput | Prisma.FocusSessionTaskCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutTaskInput | Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyTaskInputEnvelope
  set?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  disconnect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  delete?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  update?: Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutTaskInput | Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.FocusSessionTaskUpdateManyWithWhereWithoutTaskInput | Prisma.FocusSessionTaskUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.FocusSessionTaskScalarWhereInput | Prisma.FocusSessionTaskScalarWhereInput[]
}

export type FocusSessionTaskCreateNestedManyWithoutFocusSessionInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput> | Prisma.FocusSessionTaskCreateWithoutFocusSessionInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput | Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyFocusSessionInputEnvelope
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
}

export type FocusSessionTaskUncheckedCreateNestedManyWithoutFocusSessionInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput> | Prisma.FocusSessionTaskCreateWithoutFocusSessionInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput | Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyFocusSessionInputEnvelope
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
}

export type FocusSessionTaskUpdateManyWithoutFocusSessionNestedInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput> | Prisma.FocusSessionTaskCreateWithoutFocusSessionInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput | Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput[]
  upsert?: Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutFocusSessionInput | Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutFocusSessionInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyFocusSessionInputEnvelope
  set?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  disconnect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  delete?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  update?: Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutFocusSessionInput | Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutFocusSessionInput[]
  updateMany?: Prisma.FocusSessionTaskUpdateManyWithWhereWithoutFocusSessionInput | Prisma.FocusSessionTaskUpdateManyWithWhereWithoutFocusSessionInput[]
  deleteMany?: Prisma.FocusSessionTaskScalarWhereInput | Prisma.FocusSessionTaskScalarWhereInput[]
}

export type FocusSessionTaskUncheckedUpdateManyWithoutFocusSessionNestedInput = {
  create?: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput> | Prisma.FocusSessionTaskCreateWithoutFocusSessionInput[] | Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput | Prisma.FocusSessionTaskCreateOrConnectWithoutFocusSessionInput[]
  upsert?: Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutFocusSessionInput | Prisma.FocusSessionTaskUpsertWithWhereUniqueWithoutFocusSessionInput[]
  createMany?: Prisma.FocusSessionTaskCreateManyFocusSessionInputEnvelope
  set?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  disconnect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  delete?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  connect?: Prisma.FocusSessionTaskWhereUniqueInput | Prisma.FocusSessionTaskWhereUniqueInput[]
  update?: Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutFocusSessionInput | Prisma.FocusSessionTaskUpdateWithWhereUniqueWithoutFocusSessionInput[]
  updateMany?: Prisma.FocusSessionTaskUpdateManyWithWhereWithoutFocusSessionInput | Prisma.FocusSessionTaskUpdateManyWithWhereWithoutFocusSessionInput[]
  deleteMany?: Prisma.FocusSessionTaskScalarWhereInput | Prisma.FocusSessionTaskScalarWhereInput[]
}

export type FocusSessionTaskCreateWithoutTaskInput = {
  id?: string
  assignedAt?: Date | string
  focusSession: Prisma.FocusSessionCreateNestedOneWithoutTasksInput
}

export type FocusSessionTaskUncheckedCreateWithoutTaskInput = {
  id?: string
  focusSessionId: string
  assignedAt?: Date | string
}

export type FocusSessionTaskCreateOrConnectWithoutTaskInput = {
  where: Prisma.FocusSessionTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput>
}

export type FocusSessionTaskCreateManyTaskInputEnvelope = {
  data: Prisma.FocusSessionTaskCreateManyTaskInput | Prisma.FocusSessionTaskCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type FocusSessionTaskUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.FocusSessionTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.FocusSessionTaskUpdateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedCreateWithoutTaskInput>
}

export type FocusSessionTaskUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.FocusSessionTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.FocusSessionTaskUpdateWithoutTaskInput, Prisma.FocusSessionTaskUncheckedUpdateWithoutTaskInput>
}

export type FocusSessionTaskUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.FocusSessionTaskScalarWhereInput
  data: Prisma.XOR<Prisma.FocusSessionTaskUpdateManyMutationInput, Prisma.FocusSessionTaskUncheckedUpdateManyWithoutTaskInput>
}

export type FocusSessionTaskScalarWhereInput = {
  AND?: Prisma.FocusSessionTaskScalarWhereInput | Prisma.FocusSessionTaskScalarWhereInput[]
  OR?: Prisma.FocusSessionTaskScalarWhereInput[]
  NOT?: Prisma.FocusSessionTaskScalarWhereInput | Prisma.FocusSessionTaskScalarWhereInput[]
  id?: Prisma.StringFilter<"FocusSessionTask"> | string
  focusSessionId?: Prisma.StringFilter<"FocusSessionTask"> | string
  taskId?: Prisma.StringFilter<"FocusSessionTask"> | string
  assignedAt?: Prisma.DateTimeFilter<"FocusSessionTask"> | Date | string
}

export type FocusSessionTaskCreateWithoutFocusSessionInput = {
  id?: string
  assignedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutFocusSessionTasksInput
}

export type FocusSessionTaskUncheckedCreateWithoutFocusSessionInput = {
  id?: string
  taskId: string
  assignedAt?: Date | string
}

export type FocusSessionTaskCreateOrConnectWithoutFocusSessionInput = {
  where: Prisma.FocusSessionTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput>
}

export type FocusSessionTaskCreateManyFocusSessionInputEnvelope = {
  data: Prisma.FocusSessionTaskCreateManyFocusSessionInput | Prisma.FocusSessionTaskCreateManyFocusSessionInput[]
  skipDuplicates?: boolean
}

export type FocusSessionTaskUpsertWithWhereUniqueWithoutFocusSessionInput = {
  where: Prisma.FocusSessionTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.FocusSessionTaskUpdateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedUpdateWithoutFocusSessionInput>
  create: Prisma.XOR<Prisma.FocusSessionTaskCreateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedCreateWithoutFocusSessionInput>
}

export type FocusSessionTaskUpdateWithWhereUniqueWithoutFocusSessionInput = {
  where: Prisma.FocusSessionTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.FocusSessionTaskUpdateWithoutFocusSessionInput, Prisma.FocusSessionTaskUncheckedUpdateWithoutFocusSessionInput>
}

export type FocusSessionTaskUpdateManyWithWhereWithoutFocusSessionInput = {
  where: Prisma.FocusSessionTaskScalarWhereInput
  data: Prisma.XOR<Prisma.FocusSessionTaskUpdateManyMutationInput, Prisma.FocusSessionTaskUncheckedUpdateManyWithoutFocusSessionInput>
}

export type FocusSessionTaskCreateManyTaskInput = {
  id?: string
  focusSessionId: string
  assignedAt?: Date | string
}

export type FocusSessionTaskUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  focusSession?: Prisma.FocusSessionUpdateOneRequiredWithoutTasksNestedInput
}

export type FocusSessionTaskUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionTaskUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionTaskCreateManyFocusSessionInput = {
  id?: string
  taskId: string
  assignedAt?: Date | string
}

export type FocusSessionTaskUpdateWithoutFocusSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutFocusSessionTasksNestedInput
}

export type FocusSessionTaskUncheckedUpdateWithoutFocusSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusSessionTaskUncheckedUpdateManyWithoutFocusSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FocusSessionTaskSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["focusSessionTask"]>

export type FocusSessionTaskSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["focusSessionTask"]>

export type FocusSessionTaskSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["focusSessionTask"]>

export type FocusSessionTaskSelectScalar = {
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
}

export type FocusSessionTaskOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "focusSessionId" | "taskId" | "assignedAt", ExtArgs["result"]["focusSessionTask"]>
export type FocusSessionTaskInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type FocusSessionTaskIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type FocusSessionTaskIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}

export type $FocusSessionTaskPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FocusSessionTask"
  objects: {
    focusSession: Prisma.$FocusSessionPayload<ExtArgs>
    task: Prisma.$TaskPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    focusSessionId: string
    taskId: string
    assignedAt: Date
  }, ExtArgs["result"]["focusSessionTask"]>
  composites: {}
}

export type FocusSessionTaskGetPayload<S extends boolean | null | undefined | FocusSessionTaskDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload, S>

export type FocusSessionTaskCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FocusSessionTaskFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FocusSessionTaskCountAggregateInputType | true
  }

export interface FocusSessionTaskDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FocusSessionTask'], meta: { name: 'FocusSessionTask' } }
  /**
   * Find zero or one FocusSessionTask that matches the filter.
   * @param {FocusSessionTaskFindUniqueArgs} args - Arguments to find a FocusSessionTask
   * @example
   * // Get one FocusSessionTask
   * const focusSessionTask = await prisma.focusSessionTask.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FocusSessionTaskFindUniqueArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FocusSessionTask that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FocusSessionTaskFindUniqueOrThrowArgs} args - Arguments to find a FocusSessionTask
   * @example
   * // Get one FocusSessionTask
   * const focusSessionTask = await prisma.focusSessionTask.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FocusSessionTaskFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FocusSessionTask that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionTaskFindFirstArgs} args - Arguments to find a FocusSessionTask
   * @example
   * // Get one FocusSessionTask
   * const focusSessionTask = await prisma.focusSessionTask.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FocusSessionTaskFindFirstArgs>(args?: Prisma.SelectSubset<T, FocusSessionTaskFindFirstArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FocusSessionTask that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionTaskFindFirstOrThrowArgs} args - Arguments to find a FocusSessionTask
   * @example
   * // Get one FocusSessionTask
   * const focusSessionTask = await prisma.focusSessionTask.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FocusSessionTaskFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FocusSessionTaskFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FocusSessionTasks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionTaskFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FocusSessionTasks
   * const focusSessionTasks = await prisma.focusSessionTask.findMany()
   * 
   * // Get first 10 FocusSessionTasks
   * const focusSessionTasks = await prisma.focusSessionTask.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const focusSessionTaskWithIdOnly = await prisma.focusSessionTask.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FocusSessionTaskFindManyArgs>(args?: Prisma.SelectSubset<T, FocusSessionTaskFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FocusSessionTask.
   * @param {FocusSessionTaskCreateArgs} args - Arguments to create a FocusSessionTask.
   * @example
   * // Create one FocusSessionTask
   * const FocusSessionTask = await prisma.focusSessionTask.create({
   *   data: {
   *     // ... data to create a FocusSessionTask
   *   }
   * })
   * 
   */
  create<T extends FocusSessionTaskCreateArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskCreateArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FocusSessionTasks.
   * @param {FocusSessionTaskCreateManyArgs} args - Arguments to create many FocusSessionTasks.
   * @example
   * // Create many FocusSessionTasks
   * const focusSessionTask = await prisma.focusSessionTask.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FocusSessionTaskCreateManyArgs>(args?: Prisma.SelectSubset<T, FocusSessionTaskCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FocusSessionTasks and returns the data saved in the database.
   * @param {FocusSessionTaskCreateManyAndReturnArgs} args - Arguments to create many FocusSessionTasks.
   * @example
   * // Create many FocusSessionTasks
   * const focusSessionTask = await prisma.focusSessionTask.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FocusSessionTasks and only return the `id`
   * const focusSessionTaskWithIdOnly = await prisma.focusSessionTask.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FocusSessionTaskCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FocusSessionTaskCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FocusSessionTask.
   * @param {FocusSessionTaskDeleteArgs} args - Arguments to delete one FocusSessionTask.
   * @example
   * // Delete one FocusSessionTask
   * const FocusSessionTask = await prisma.focusSessionTask.delete({
   *   where: {
   *     // ... filter to delete one FocusSessionTask
   *   }
   * })
   * 
   */
  delete<T extends FocusSessionTaskDeleteArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskDeleteArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FocusSessionTask.
   * @param {FocusSessionTaskUpdateArgs} args - Arguments to update one FocusSessionTask.
   * @example
   * // Update one FocusSessionTask
   * const focusSessionTask = await prisma.focusSessionTask.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FocusSessionTaskUpdateArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskUpdateArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FocusSessionTasks.
   * @param {FocusSessionTaskDeleteManyArgs} args - Arguments to filter FocusSessionTasks to delete.
   * @example
   * // Delete a few FocusSessionTasks
   * const { count } = await prisma.focusSessionTask.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FocusSessionTaskDeleteManyArgs>(args?: Prisma.SelectSubset<T, FocusSessionTaskDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FocusSessionTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionTaskUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FocusSessionTasks
   * const focusSessionTask = await prisma.focusSessionTask.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FocusSessionTaskUpdateManyArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FocusSessionTasks and returns the data updated in the database.
   * @param {FocusSessionTaskUpdateManyAndReturnArgs} args - Arguments to update many FocusSessionTasks.
   * @example
   * // Update many FocusSessionTasks
   * const focusSessionTask = await prisma.focusSessionTask.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FocusSessionTasks and only return the `id`
   * const focusSessionTaskWithIdOnly = await prisma.focusSessionTask.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FocusSessionTaskUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FocusSessionTask.
   * @param {FocusSessionTaskUpsertArgs} args - Arguments to update or create a FocusSessionTask.
   * @example
   * // Update or create a FocusSessionTask
   * const focusSessionTask = await prisma.focusSessionTask.upsert({
   *   create: {
   *     // ... data to create a FocusSessionTask
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FocusSessionTask we want to update
   *   }
   * })
   */
  upsert<T extends FocusSessionTaskUpsertArgs>(args: Prisma.SelectSubset<T, FocusSessionTaskUpsertArgs<ExtArgs>>): Prisma.Prisma__FocusSessionTaskClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionTaskPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FocusSessionTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionTaskCountArgs} args - Arguments to filter FocusSessionTasks to count.
   * @example
   * // Count the number of FocusSessionTasks
   * const count = await prisma.focusSessionTask.count({
   *   where: {
   *     // ... the filter for the FocusSessionTasks we want to count
   *   }
   * })
  **/
  count<T extends FocusSessionTaskCountArgs>(
    args?: Prisma.Subset<T, FocusSessionTaskCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FocusSessionTaskCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FocusSessionTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionTaskAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FocusSessionTaskAggregateArgs>(args: Prisma.Subset<T, FocusSessionTaskAggregateArgs>): Prisma.PrismaPromise<GetFocusSessionTaskAggregateType<T>>

  /**
   * Group by FocusSessionTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusSessionTaskGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FocusSessionTaskGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FocusSessionTaskGroupByArgs['orderBy'] }
      : { orderBy?: FocusSessionTaskGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FocusSessionTaskGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFocusSessionTaskGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FocusSessionTask model
 */
readonly fields: FocusSessionTaskFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FocusSessionTask.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FocusSessionTaskClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  focusSession<T extends Prisma.FocusSessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FocusSessionDefaultArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FocusSessionTask model
 */
export interface FocusSessionTaskFieldRefs {
  readonly id: Prisma.FieldRef<"FocusSessionTask", 'String'>
  readonly focusSessionId: Prisma.FieldRef<"FocusSessionTask", 'String'>
  readonly taskId: Prisma.FieldRef<"FocusSessionTask", 'String'>
  readonly assignedAt: Prisma.FieldRef<"FocusSessionTask", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FocusSessionTask findUnique
 */
export type FocusSessionTaskFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * Filter, which FocusSessionTask to fetch.
   */
  where: Prisma.FocusSessionTaskWhereUniqueInput
}

/**
 * FocusSessionTask findUniqueOrThrow
 */
export type FocusSessionTaskFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * Filter, which FocusSessionTask to fetch.
   */
  where: Prisma.FocusSessionTaskWhereUniqueInput
}

/**
 * FocusSessionTask findFirst
 */
export type FocusSessionTaskFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * Filter, which FocusSessionTask to fetch.
   */
  where?: Prisma.FocusSessionTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessionTasks to fetch.
   */
  orderBy?: Prisma.FocusSessionTaskOrderByWithRelationInput | Prisma.FocusSessionTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FocusSessionTasks.
   */
  cursor?: Prisma.FocusSessionTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessionTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessionTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusSessionTasks.
   */
  distinct?: Prisma.FocusSessionTaskScalarFieldEnum | Prisma.FocusSessionTaskScalarFieldEnum[]
}

/**
 * FocusSessionTask findFirstOrThrow
 */
export type FocusSessionTaskFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * Filter, which FocusSessionTask to fetch.
   */
  where?: Prisma.FocusSessionTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessionTasks to fetch.
   */
  orderBy?: Prisma.FocusSessionTaskOrderByWithRelationInput | Prisma.FocusSessionTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FocusSessionTasks.
   */
  cursor?: Prisma.FocusSessionTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessionTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessionTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusSessionTasks.
   */
  distinct?: Prisma.FocusSessionTaskScalarFieldEnum | Prisma.FocusSessionTaskScalarFieldEnum[]
}

/**
 * FocusSessionTask findMany
 */
export type FocusSessionTaskFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * Filter, which FocusSessionTasks to fetch.
   */
  where?: Prisma.FocusSessionTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusSessionTasks to fetch.
   */
  orderBy?: Prisma.FocusSessionTaskOrderByWithRelationInput | Prisma.FocusSessionTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FocusSessionTasks.
   */
  cursor?: Prisma.FocusSessionTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusSessionTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusSessionTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusSessionTasks.
   */
  distinct?: Prisma.FocusSessionTaskScalarFieldEnum | Prisma.FocusSessionTaskScalarFieldEnum[]
}

/**
 * FocusSessionTask create
 */
export type FocusSessionTaskCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * The data needed to create a FocusSessionTask.
   */
  data: Prisma.XOR<Prisma.FocusSessionTaskCreateInput, Prisma.FocusSessionTaskUncheckedCreateInput>
}

/**
 * FocusSessionTask createMany
 */
export type FocusSessionTaskCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FocusSessionTasks.
   */
  data: Prisma.FocusSessionTaskCreateManyInput | Prisma.FocusSessionTaskCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FocusSessionTask createManyAndReturn
 */
export type FocusSessionTaskCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * The data used to create many FocusSessionTasks.
   */
  data: Prisma.FocusSessionTaskCreateManyInput | Prisma.FocusSessionTaskCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FocusSessionTask update
 */
export type FocusSessionTaskUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * The data needed to update a FocusSessionTask.
   */
  data: Prisma.XOR<Prisma.FocusSessionTaskUpdateInput, Prisma.FocusSessionTaskUncheckedUpdateInput>
  /**
   * Choose, which FocusSessionTask to update.
   */
  where: Prisma.FocusSessionTaskWhereUniqueInput
}

/**
 * FocusSessionTask updateMany
 */
export type FocusSessionTaskUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FocusSessionTasks.
   */
  data: Prisma.XOR<Prisma.FocusSessionTaskUpdateManyMutationInput, Prisma.FocusSessionTaskUncheckedUpdateManyInput>
  /**
   * Filter which FocusSessionTasks to update
   */
  where?: Prisma.FocusSessionTaskWhereInput
  /**
   * Limit how many FocusSessionTasks to update.
   */
  limit?: number
}

/**
 * FocusSessionTask updateManyAndReturn
 */
export type FocusSessionTaskUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * The data used to update FocusSessionTasks.
   */
  data: Prisma.XOR<Prisma.FocusSessionTaskUpdateManyMutationInput, Prisma.FocusSessionTaskUncheckedUpdateManyInput>
  /**
   * Filter which FocusSessionTasks to update
   */
  where?: Prisma.FocusSessionTaskWhereInput
  /**
   * Limit how many FocusSessionTasks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FocusSessionTask upsert
 */
export type FocusSessionTaskUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * The filter to search for the FocusSessionTask to update in case it exists.
   */
  where: Prisma.FocusSessionTaskWhereUniqueInput
  /**
   * In case the FocusSessionTask found by the `where` argument doesn't exist, create a new FocusSessionTask with this data.
   */
  create: Prisma.XOR<Prisma.FocusSessionTaskCreateInput, Prisma.FocusSessionTaskUncheckedCreateInput>
  /**
   * In case the FocusSessionTask was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FocusSessionTaskUpdateInput, Prisma.FocusSessionTaskUncheckedUpdateInput>
}

/**
 * FocusSessionTask delete
 */
export type FocusSessionTaskDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
  /**
   * Filter which FocusSessionTask to delete.
   */
  where: Prisma.FocusSessionTaskWhereUniqueInput
}

/**
 * FocusSessionTask deleteMany
 */
export type FocusSessionTaskDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FocusSessionTasks to delete
   */
  where?: Prisma.FocusSessionTaskWhereInput
  /**
   * Limit how many FocusSessionTasks to delete.
   */
  limit?: number
}

/**
 * FocusSessionTask without action
 */
export type FocusSessionTaskDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusSessionTask
   */
  select?: Prisma.FocusSessionTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusSessionTask
   */
  omit?: Prisma.FocusSessionTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusSessionTaskInclude<ExtArgs> | null
}
