
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProofType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProofType
 * 
 */
export type ProofTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$ProofTypePayload>

export type AggregateProofType = {
  _count: ProofTypeCountAggregateOutputType | null
  _min: ProofTypeMinAggregateOutputType | null
  _max: ProofTypeMaxAggregateOutputType | null
}

export type ProofTypeMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
}

export type ProofTypeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
}

export type ProofTypeCountAggregateOutputType = {
  id: number
  name: number
  description: number
  _all: number
}


export type ProofTypeMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type ProofTypeMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type ProofTypeCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  _all?: true
}

export type ProofTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProofType to aggregate.
   */
  where?: Prisma.ProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProofTypes to fetch.
   */
  orderBy?: Prisma.ProofTypeOrderByWithRelationInput | Prisma.ProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProofTypes
  **/
  _count?: true | ProofTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProofTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProofTypeMaxAggregateInputType
}

export type GetProofTypeAggregateType<T extends ProofTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateProofType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProofType[P]>
    : Prisma.GetScalarType<T[P], AggregateProofType[P]>
}




export type ProofTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProofTypeWhereInput
  orderBy?: Prisma.ProofTypeOrderByWithAggregationInput | Prisma.ProofTypeOrderByWithAggregationInput[]
  by: Prisma.ProofTypeScalarFieldEnum[] | Prisma.ProofTypeScalarFieldEnum
  having?: Prisma.ProofTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProofTypeCountAggregateInputType | true
  _min?: ProofTypeMinAggregateInputType
  _max?: ProofTypeMaxAggregateInputType
}

export type ProofTypeGroupByOutputType = {
  id: string
  name: string
  description: string | null
  _count: ProofTypeCountAggregateOutputType | null
  _min: ProofTypeMinAggregateOutputType | null
  _max: ProofTypeMaxAggregateOutputType | null
}

export type GetProofTypeGroupByPayload<T extends ProofTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProofTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProofTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProofTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProofTypeGroupByOutputType[P]>
      }
    >
  >



export type ProofTypeWhereInput = {
  AND?: Prisma.ProofTypeWhereInput | Prisma.ProofTypeWhereInput[]
  OR?: Prisma.ProofTypeWhereInput[]
  NOT?: Prisma.ProofTypeWhereInput | Prisma.ProofTypeWhereInput[]
  id?: Prisma.StringFilter<"ProofType"> | string
  name?: Prisma.StringFilter<"ProofType"> | string
  description?: Prisma.StringNullableFilter<"ProofType"> | string | null
  proofs?: Prisma.ProofListRelationFilter
  taskTypes?: Prisma.TaskTypeProofTypeListRelationFilter
}

export type ProofTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  proofs?: Prisma.ProofOrderByRelationAggregateInput
  taskTypes?: Prisma.TaskTypeProofTypeOrderByRelationAggregateInput
}

export type ProofTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProofTypeWhereInput | Prisma.ProofTypeWhereInput[]
  OR?: Prisma.ProofTypeWhereInput[]
  NOT?: Prisma.ProofTypeWhereInput | Prisma.ProofTypeWhereInput[]
  name?: Prisma.StringFilter<"ProofType"> | string
  description?: Prisma.StringNullableFilter<"ProofType"> | string | null
  proofs?: Prisma.ProofListRelationFilter
  taskTypes?: Prisma.TaskTypeProofTypeListRelationFilter
}, "id">

export type ProofTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProofTypeCountOrderByAggregateInput
  _max?: Prisma.ProofTypeMaxOrderByAggregateInput
  _min?: Prisma.ProofTypeMinOrderByAggregateInput
}

export type ProofTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProofTypeScalarWhereWithAggregatesInput | Prisma.ProofTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProofTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProofTypeScalarWhereWithAggregatesInput | Prisma.ProofTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProofType"> | string
  name?: Prisma.StringWithAggregatesFilter<"ProofType"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"ProofType"> | string | null
}

export type ProofTypeCreateInput = {
  id?: string
  name: string
  description?: string | null
  proofs?: Prisma.ProofCreateNestedManyWithoutProofTypeInput
  taskTypes?: Prisma.TaskTypeProofTypeCreateNestedManyWithoutProofTypeInput
}

export type ProofTypeUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  proofs?: Prisma.ProofUncheckedCreateNestedManyWithoutProofTypeInput
  taskTypes?: Prisma.TaskTypeProofTypeUncheckedCreateNestedManyWithoutProofTypeInput
}

export type ProofTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proofs?: Prisma.ProofUpdateManyWithoutProofTypeNestedInput
  taskTypes?: Prisma.TaskTypeProofTypeUpdateManyWithoutProofTypeNestedInput
}

export type ProofTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proofs?: Prisma.ProofUncheckedUpdateManyWithoutProofTypeNestedInput
  taskTypes?: Prisma.TaskTypeProofTypeUncheckedUpdateManyWithoutProofTypeNestedInput
}

export type ProofTypeCreateManyInput = {
  id?: string
  name: string
  description?: string | null
}

export type ProofTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProofTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProofTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProofTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProofTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ProofTypeScalarRelationFilter = {
  is?: Prisma.ProofTypeWhereInput
  isNot?: Prisma.ProofTypeWhereInput
}

export type ProofTypeCreateNestedOneWithoutTaskTypesInput = {
  create?: Prisma.XOR<Prisma.ProofTypeCreateWithoutTaskTypesInput, Prisma.ProofTypeUncheckedCreateWithoutTaskTypesInput>
  connectOrCreate?: Prisma.ProofTypeCreateOrConnectWithoutTaskTypesInput
  connect?: Prisma.ProofTypeWhereUniqueInput
}

export type ProofTypeUpdateOneRequiredWithoutTaskTypesNestedInput = {
  create?: Prisma.XOR<Prisma.ProofTypeCreateWithoutTaskTypesInput, Prisma.ProofTypeUncheckedCreateWithoutTaskTypesInput>
  connectOrCreate?: Prisma.ProofTypeCreateOrConnectWithoutTaskTypesInput
  upsert?: Prisma.ProofTypeUpsertWithoutTaskTypesInput
  connect?: Prisma.ProofTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProofTypeUpdateToOneWithWhereWithoutTaskTypesInput, Prisma.ProofTypeUpdateWithoutTaskTypesInput>, Prisma.ProofTypeUncheckedUpdateWithoutTaskTypesInput>
}

export type ProofTypeCreateNestedOneWithoutProofsInput = {
  create?: Prisma.XOR<Prisma.ProofTypeCreateWithoutProofsInput, Prisma.ProofTypeUncheckedCreateWithoutProofsInput>
  connectOrCreate?: Prisma.ProofTypeCreateOrConnectWithoutProofsInput
  connect?: Prisma.ProofTypeWhereUniqueInput
}

export type ProofTypeUpdateOneRequiredWithoutProofsNestedInput = {
  create?: Prisma.XOR<Prisma.ProofTypeCreateWithoutProofsInput, Prisma.ProofTypeUncheckedCreateWithoutProofsInput>
  connectOrCreate?: Prisma.ProofTypeCreateOrConnectWithoutProofsInput
  upsert?: Prisma.ProofTypeUpsertWithoutProofsInput
  connect?: Prisma.ProofTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProofTypeUpdateToOneWithWhereWithoutProofsInput, Prisma.ProofTypeUpdateWithoutProofsInput>, Prisma.ProofTypeUncheckedUpdateWithoutProofsInput>
}

export type ProofTypeCreateWithoutTaskTypesInput = {
  id?: string
  name: string
  description?: string | null
  proofs?: Prisma.ProofCreateNestedManyWithoutProofTypeInput
}

export type ProofTypeUncheckedCreateWithoutTaskTypesInput = {
  id?: string
  name: string
  description?: string | null
  proofs?: Prisma.ProofUncheckedCreateNestedManyWithoutProofTypeInput
}

export type ProofTypeCreateOrConnectWithoutTaskTypesInput = {
  where: Prisma.ProofTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.ProofTypeCreateWithoutTaskTypesInput, Prisma.ProofTypeUncheckedCreateWithoutTaskTypesInput>
}

export type ProofTypeUpsertWithoutTaskTypesInput = {
  update: Prisma.XOR<Prisma.ProofTypeUpdateWithoutTaskTypesInput, Prisma.ProofTypeUncheckedUpdateWithoutTaskTypesInput>
  create: Prisma.XOR<Prisma.ProofTypeCreateWithoutTaskTypesInput, Prisma.ProofTypeUncheckedCreateWithoutTaskTypesInput>
  where?: Prisma.ProofTypeWhereInput
}

export type ProofTypeUpdateToOneWithWhereWithoutTaskTypesInput = {
  where?: Prisma.ProofTypeWhereInput
  data: Prisma.XOR<Prisma.ProofTypeUpdateWithoutTaskTypesInput, Prisma.ProofTypeUncheckedUpdateWithoutTaskTypesInput>
}

export type ProofTypeUpdateWithoutTaskTypesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proofs?: Prisma.ProofUpdateManyWithoutProofTypeNestedInput
}

export type ProofTypeUncheckedUpdateWithoutTaskTypesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  proofs?: Prisma.ProofUncheckedUpdateManyWithoutProofTypeNestedInput
}

export type ProofTypeCreateWithoutProofsInput = {
  id?: string
  name: string
  description?: string | null
  taskTypes?: Prisma.TaskTypeProofTypeCreateNestedManyWithoutProofTypeInput
}

export type ProofTypeUncheckedCreateWithoutProofsInput = {
  id?: string
  name: string
  description?: string | null
  taskTypes?: Prisma.TaskTypeProofTypeUncheckedCreateNestedManyWithoutProofTypeInput
}

export type ProofTypeCreateOrConnectWithoutProofsInput = {
  where: Prisma.ProofTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.ProofTypeCreateWithoutProofsInput, Prisma.ProofTypeUncheckedCreateWithoutProofsInput>
}

export type ProofTypeUpsertWithoutProofsInput = {
  update: Prisma.XOR<Prisma.ProofTypeUpdateWithoutProofsInput, Prisma.ProofTypeUncheckedUpdateWithoutProofsInput>
  create: Prisma.XOR<Prisma.ProofTypeCreateWithoutProofsInput, Prisma.ProofTypeUncheckedCreateWithoutProofsInput>
  where?: Prisma.ProofTypeWhereInput
}

export type ProofTypeUpdateToOneWithWhereWithoutProofsInput = {
  where?: Prisma.ProofTypeWhereInput
  data: Prisma.XOR<Prisma.ProofTypeUpdateWithoutProofsInput, Prisma.ProofTypeUncheckedUpdateWithoutProofsInput>
}

export type ProofTypeUpdateWithoutProofsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskTypes?: Prisma.TaskTypeProofTypeUpdateManyWithoutProofTypeNestedInput
}

export type ProofTypeUncheckedUpdateWithoutProofsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskTypes?: Prisma.TaskTypeProofTypeUncheckedUpdateManyWithoutProofTypeNestedInput
}


/**
 * Count Type ProofTypeCountOutputType
 */

export type ProofTypeCountOutputType = {
  proofs: number
  taskTypes: number
}

export type ProofTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  proofs?: boolean | ProofTypeCountOutputTypeCountProofsArgs
  taskTypes?: boolean | ProofTypeCountOutputTypeCountTaskTypesArgs
}

/**
 * ProofTypeCountOutputType without action
 */
export type ProofTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofTypeCountOutputType
   */
  select?: Prisma.ProofTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProofTypeCountOutputType without action
 */
export type ProofTypeCountOutputTypeCountProofsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProofWhereInput
}

/**
 * ProofTypeCountOutputType without action
 */
export type ProofTypeCountOutputTypeCountTaskTypesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskTypeProofTypeWhereInput
}


export type ProofTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  proofs?: boolean | Prisma.ProofType$proofsArgs<ExtArgs>
  taskTypes?: boolean | Prisma.ProofType$taskTypesArgs<ExtArgs>
  _count?: boolean | Prisma.ProofTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proofType"]>

export type ProofTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
}, ExtArgs["result"]["proofType"]>

export type ProofTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
}, ExtArgs["result"]["proofType"]>

export type ProofTypeSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
}

export type ProofTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description", ExtArgs["result"]["proofType"]>
export type ProofTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  proofs?: boolean | Prisma.ProofType$proofsArgs<ExtArgs>
  taskTypes?: boolean | Prisma.ProofType$taskTypesArgs<ExtArgs>
  _count?: boolean | Prisma.ProofTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProofTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProofTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProofTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProofType"
  objects: {
    proofs: Prisma.$ProofPayload<ExtArgs>[]
    taskTypes: Prisma.$TaskTypeProofTypePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
  }, ExtArgs["result"]["proofType"]>
  composites: {}
}

export type ProofTypeGetPayload<S extends boolean | null | undefined | ProofTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProofTypePayload, S>

export type ProofTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProofTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProofTypeCountAggregateInputType | true
  }

export interface ProofTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProofType'], meta: { name: 'ProofType' } }
  /**
   * Find zero or one ProofType that matches the filter.
   * @param {ProofTypeFindUniqueArgs} args - Arguments to find a ProofType
   * @example
   * // Get one ProofType
   * const proofType = await prisma.proofType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProofTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, ProofTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProofType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProofTypeFindUniqueOrThrowArgs} args - Arguments to find a ProofType
   * @example
   * // Get one ProofType
   * const proofType = await prisma.proofType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProofTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProofTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProofType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofTypeFindFirstArgs} args - Arguments to find a ProofType
   * @example
   * // Get one ProofType
   * const proofType = await prisma.proofType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProofTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, ProofTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProofType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofTypeFindFirstOrThrowArgs} args - Arguments to find a ProofType
   * @example
   * // Get one ProofType
   * const proofType = await prisma.proofType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProofTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProofTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProofTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProofTypes
   * const proofTypes = await prisma.proofType.findMany()
   * 
   * // Get first 10 ProofTypes
   * const proofTypes = await prisma.proofType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const proofTypeWithIdOnly = await prisma.proofType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProofTypeFindManyArgs>(args?: Prisma.SelectSubset<T, ProofTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProofType.
   * @param {ProofTypeCreateArgs} args - Arguments to create a ProofType.
   * @example
   * // Create one ProofType
   * const ProofType = await prisma.proofType.create({
   *   data: {
   *     // ... data to create a ProofType
   *   }
   * })
   * 
   */
  create<T extends ProofTypeCreateArgs>(args: Prisma.SelectSubset<T, ProofTypeCreateArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProofTypes.
   * @param {ProofTypeCreateManyArgs} args - Arguments to create many ProofTypes.
   * @example
   * // Create many ProofTypes
   * const proofType = await prisma.proofType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProofTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, ProofTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProofTypes and returns the data saved in the database.
   * @param {ProofTypeCreateManyAndReturnArgs} args - Arguments to create many ProofTypes.
   * @example
   * // Create many ProofTypes
   * const proofType = await prisma.proofType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProofTypes and only return the `id`
   * const proofTypeWithIdOnly = await prisma.proofType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProofTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProofTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProofType.
   * @param {ProofTypeDeleteArgs} args - Arguments to delete one ProofType.
   * @example
   * // Delete one ProofType
   * const ProofType = await prisma.proofType.delete({
   *   where: {
   *     // ... filter to delete one ProofType
   *   }
   * })
   * 
   */
  delete<T extends ProofTypeDeleteArgs>(args: Prisma.SelectSubset<T, ProofTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProofType.
   * @param {ProofTypeUpdateArgs} args - Arguments to update one ProofType.
   * @example
   * // Update one ProofType
   * const proofType = await prisma.proofType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProofTypeUpdateArgs>(args: Prisma.SelectSubset<T, ProofTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProofTypes.
   * @param {ProofTypeDeleteManyArgs} args - Arguments to filter ProofTypes to delete.
   * @example
   * // Delete a few ProofTypes
   * const { count } = await prisma.proofType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProofTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProofTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProofTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProofTypes
   * const proofType = await prisma.proofType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProofTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, ProofTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProofTypes and returns the data updated in the database.
   * @param {ProofTypeUpdateManyAndReturnArgs} args - Arguments to update many ProofTypes.
   * @example
   * // Update many ProofTypes
   * const proofType = await prisma.proofType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProofTypes and only return the `id`
   * const proofTypeWithIdOnly = await prisma.proofType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProofTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProofTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProofType.
   * @param {ProofTypeUpsertArgs} args - Arguments to update or create a ProofType.
   * @example
   * // Update or create a ProofType
   * const proofType = await prisma.proofType.upsert({
   *   create: {
   *     // ... data to create a ProofType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProofType we want to update
   *   }
   * })
   */
  upsert<T extends ProofTypeUpsertArgs>(args: Prisma.SelectSubset<T, ProofTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProofTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofTypeCountArgs} args - Arguments to filter ProofTypes to count.
   * @example
   * // Count the number of ProofTypes
   * const count = await prisma.proofType.count({
   *   where: {
   *     // ... the filter for the ProofTypes we want to count
   *   }
   * })
  **/
  count<T extends ProofTypeCountArgs>(
    args?: Prisma.Subset<T, ProofTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProofTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProofType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProofTypeAggregateArgs>(args: Prisma.Subset<T, ProofTypeAggregateArgs>): Prisma.PrismaPromise<GetProofTypeAggregateType<T>>

  /**
   * Group by ProofType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProofTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProofTypeGroupByArgs['orderBy'] }
      : { orderBy?: ProofTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProofTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProofTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProofType model
 */
readonly fields: ProofTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProofType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProofTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  proofs<T extends Prisma.ProofType$proofsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProofType$proofsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  taskTypes<T extends Prisma.ProofType$taskTypesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProofType$taskTypesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProofType model
 */
export interface ProofTypeFieldRefs {
  readonly id: Prisma.FieldRef<"ProofType", 'String'>
  readonly name: Prisma.FieldRef<"ProofType", 'String'>
  readonly description: Prisma.FieldRef<"ProofType", 'String'>
}
    

// Custom InputTypes
/**
 * ProofType findUnique
 */
export type ProofTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which ProofType to fetch.
   */
  where: Prisma.ProofTypeWhereUniqueInput
}

/**
 * ProofType findUniqueOrThrow
 */
export type ProofTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which ProofType to fetch.
   */
  where: Prisma.ProofTypeWhereUniqueInput
}

/**
 * ProofType findFirst
 */
export type ProofTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which ProofType to fetch.
   */
  where?: Prisma.ProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProofTypes to fetch.
   */
  orderBy?: Prisma.ProofTypeOrderByWithRelationInput | Prisma.ProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProofTypes.
   */
  cursor?: Prisma.ProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProofTypes.
   */
  distinct?: Prisma.ProofTypeScalarFieldEnum | Prisma.ProofTypeScalarFieldEnum[]
}

/**
 * ProofType findFirstOrThrow
 */
export type ProofTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which ProofType to fetch.
   */
  where?: Prisma.ProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProofTypes to fetch.
   */
  orderBy?: Prisma.ProofTypeOrderByWithRelationInput | Prisma.ProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProofTypes.
   */
  cursor?: Prisma.ProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProofTypes.
   */
  distinct?: Prisma.ProofTypeScalarFieldEnum | Prisma.ProofTypeScalarFieldEnum[]
}

/**
 * ProofType findMany
 */
export type ProofTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which ProofTypes to fetch.
   */
  where?: Prisma.ProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProofTypes to fetch.
   */
  orderBy?: Prisma.ProofTypeOrderByWithRelationInput | Prisma.ProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProofTypes.
   */
  cursor?: Prisma.ProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProofTypes.
   */
  distinct?: Prisma.ProofTypeScalarFieldEnum | Prisma.ProofTypeScalarFieldEnum[]
}

/**
 * ProofType create
 */
export type ProofTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a ProofType.
   */
  data: Prisma.XOR<Prisma.ProofTypeCreateInput, Prisma.ProofTypeUncheckedCreateInput>
}

/**
 * ProofType createMany
 */
export type ProofTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProofTypes.
   */
  data: Prisma.ProofTypeCreateManyInput | Prisma.ProofTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProofType createManyAndReturn
 */
export type ProofTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * The data used to create many ProofTypes.
   */
  data: Prisma.ProofTypeCreateManyInput | Prisma.ProofTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProofType update
 */
export type ProofTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a ProofType.
   */
  data: Prisma.XOR<Prisma.ProofTypeUpdateInput, Prisma.ProofTypeUncheckedUpdateInput>
  /**
   * Choose, which ProofType to update.
   */
  where: Prisma.ProofTypeWhereUniqueInput
}

/**
 * ProofType updateMany
 */
export type ProofTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProofTypes.
   */
  data: Prisma.XOR<Prisma.ProofTypeUpdateManyMutationInput, Prisma.ProofTypeUncheckedUpdateManyInput>
  /**
   * Filter which ProofTypes to update
   */
  where?: Prisma.ProofTypeWhereInput
  /**
   * Limit how many ProofTypes to update.
   */
  limit?: number
}

/**
 * ProofType updateManyAndReturn
 */
export type ProofTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * The data used to update ProofTypes.
   */
  data: Prisma.XOR<Prisma.ProofTypeUpdateManyMutationInput, Prisma.ProofTypeUncheckedUpdateManyInput>
  /**
   * Filter which ProofTypes to update
   */
  where?: Prisma.ProofTypeWhereInput
  /**
   * Limit how many ProofTypes to update.
   */
  limit?: number
}

/**
 * ProofType upsert
 */
export type ProofTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the ProofType to update in case it exists.
   */
  where: Prisma.ProofTypeWhereUniqueInput
  /**
   * In case the ProofType found by the `where` argument doesn't exist, create a new ProofType with this data.
   */
  create: Prisma.XOR<Prisma.ProofTypeCreateInput, Prisma.ProofTypeUncheckedCreateInput>
  /**
   * In case the ProofType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProofTypeUpdateInput, Prisma.ProofTypeUncheckedUpdateInput>
}

/**
 * ProofType delete
 */
export type ProofTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
  /**
   * Filter which ProofType to delete.
   */
  where: Prisma.ProofTypeWhereUniqueInput
}

/**
 * ProofType deleteMany
 */
export type ProofTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProofTypes to delete
   */
  where?: Prisma.ProofTypeWhereInput
  /**
   * Limit how many ProofTypes to delete.
   */
  limit?: number
}

/**
 * ProofType.proofs
 */
export type ProofType$proofsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  where?: Prisma.ProofWhereInput
  orderBy?: Prisma.ProofOrderByWithRelationInput | Prisma.ProofOrderByWithRelationInput[]
  cursor?: Prisma.ProofWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProofScalarFieldEnum | Prisma.ProofScalarFieldEnum[]
}

/**
 * ProofType.taskTypes
 */
export type ProofType$taskTypesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  where?: Prisma.TaskTypeProofTypeWhereInput
  orderBy?: Prisma.TaskTypeProofTypeOrderByWithRelationInput | Prisma.TaskTypeProofTypeOrderByWithRelationInput[]
  cursor?: Prisma.TaskTypeProofTypeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TaskTypeProofTypeScalarFieldEnum | Prisma.TaskTypeProofTypeScalarFieldEnum[]
}

/**
 * ProofType without action
 */
export type ProofTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofType
   */
  select?: Prisma.ProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProofType
   */
  omit?: Prisma.ProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofTypeInclude<ExtArgs> | null
}
