
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Proof` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Proof
 * 
 */
export type ProofModel = runtime.Types.Result.DefaultSelection<Prisma.$ProofPayload>

export type AggregateProof = {
  _count: ProofCountAggregateOutputType | null
  _min: ProofMinAggregateOutputType | null
  _max: ProofMaxAggregateOutputType | null
}

export type ProofMinAggregateOutputType = {
  id: string | null
  proofData: string | null
  taskId: string | null
  userId: string | null
  proofTypeId: string | null
}

export type ProofMaxAggregateOutputType = {
  id: string | null
  proofData: string | null
  taskId: string | null
  userId: string | null
  proofTypeId: string | null
}

export type ProofCountAggregateOutputType = {
  id: number
  proofData: number
  taskId: number
  userId: number
  proofTypeId: number
  _all: number
}


export type ProofMinAggregateInputType = {
  id?: true
  proofData?: true
  taskId?: true
  userId?: true
  proofTypeId?: true
}

export type ProofMaxAggregateInputType = {
  id?: true
  proofData?: true
  taskId?: true
  userId?: true
  proofTypeId?: true
}

export type ProofCountAggregateInputType = {
  id?: true
  proofData?: true
  taskId?: true
  userId?: true
  proofTypeId?: true
  _all?: true
}

export type ProofAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proof to aggregate.
   */
  where?: Prisma.ProofWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proofs to fetch.
   */
  orderBy?: Prisma.ProofOrderByWithRelationInput | Prisma.ProofOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProofWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proofs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proofs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Proofs
  **/
  _count?: true | ProofCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProofMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProofMaxAggregateInputType
}

export type GetProofAggregateType<T extends ProofAggregateArgs> = {
      [P in keyof T & keyof AggregateProof]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProof[P]>
    : Prisma.GetScalarType<T[P], AggregateProof[P]>
}




export type ProofGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProofWhereInput
  orderBy?: Prisma.ProofOrderByWithAggregationInput | Prisma.ProofOrderByWithAggregationInput[]
  by: Prisma.ProofScalarFieldEnum[] | Prisma.ProofScalarFieldEnum
  having?: Prisma.ProofScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProofCountAggregateInputType | true
  _min?: ProofMinAggregateInputType
  _max?: ProofMaxAggregateInputType
}

export type ProofGroupByOutputType = {
  id: string
  proofData: string
  taskId: string
  userId: string
  proofTypeId: string
  _count: ProofCountAggregateOutputType | null
  _min: ProofMinAggregateOutputType | null
  _max: ProofMaxAggregateOutputType | null
}

export type GetProofGroupByPayload<T extends ProofGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProofGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProofGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProofGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProofGroupByOutputType[P]>
      }
    >
  >



export type ProofWhereInput = {
  AND?: Prisma.ProofWhereInput | Prisma.ProofWhereInput[]
  OR?: Prisma.ProofWhereInput[]
  NOT?: Prisma.ProofWhereInput | Prisma.ProofWhereInput[]
  id?: Prisma.StringFilter<"Proof"> | string
  proofData?: Prisma.StringFilter<"Proof"> | string
  taskId?: Prisma.StringFilter<"Proof"> | string
  userId?: Prisma.StringFilter<"Proof"> | string
  proofTypeId?: Prisma.StringFilter<"Proof"> | string
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  proofType?: Prisma.XOR<Prisma.ProofTypeScalarRelationFilter, Prisma.ProofTypeWhereInput>
  verifications?: Prisma.VerificationListRelationFilter
}

export type ProofOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  proofData?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
  task?: Prisma.TaskOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  proofType?: Prisma.ProofTypeOrderByWithRelationInput
  verifications?: Prisma.VerificationOrderByRelationAggregateInput
}

export type ProofWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProofWhereInput | Prisma.ProofWhereInput[]
  OR?: Prisma.ProofWhereInput[]
  NOT?: Prisma.ProofWhereInput | Prisma.ProofWhereInput[]
  proofData?: Prisma.StringFilter<"Proof"> | string
  taskId?: Prisma.StringFilter<"Proof"> | string
  userId?: Prisma.StringFilter<"Proof"> | string
  proofTypeId?: Prisma.StringFilter<"Proof"> | string
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  proofType?: Prisma.XOR<Prisma.ProofTypeScalarRelationFilter, Prisma.ProofTypeWhereInput>
  verifications?: Prisma.VerificationListRelationFilter
}, "id">

export type ProofOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  proofData?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
  _count?: Prisma.ProofCountOrderByAggregateInput
  _max?: Prisma.ProofMaxOrderByAggregateInput
  _min?: Prisma.ProofMinOrderByAggregateInput
}

export type ProofScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProofScalarWhereWithAggregatesInput | Prisma.ProofScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProofScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProofScalarWhereWithAggregatesInput | Prisma.ProofScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Proof"> | string
  proofData?: Prisma.StringWithAggregatesFilter<"Proof"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"Proof"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Proof"> | string
  proofTypeId?: Prisma.StringWithAggregatesFilter<"Proof"> | string
}

export type ProofCreateInput = {
  id?: string
  proofData: string
  task: Prisma.TaskCreateNestedOneWithoutProofsInput
  user: Prisma.UserCreateNestedOneWithoutProofsInput
  proofType: Prisma.ProofTypeCreateNestedOneWithoutProofsInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutProofInput
}

export type ProofUncheckedCreateInput = {
  id?: string
  proofData: string
  taskId: string
  userId: string
  proofTypeId: string
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutProofInput
}

export type ProofUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.TaskUpdateOneRequiredWithoutProofsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutProofsNestedInput
  proofType?: Prisma.ProofTypeUpdateOneRequiredWithoutProofsNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutProofNestedInput
}

export type ProofUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutProofNestedInput
}

export type ProofCreateManyInput = {
  id?: string
  proofData: string
  taskId: string
  userId: string
  proofTypeId: string
}

export type ProofUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProofUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProofListRelationFilter = {
  every?: Prisma.ProofWhereInput
  some?: Prisma.ProofWhereInput
  none?: Prisma.ProofWhereInput
}

export type ProofOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProofCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  proofData?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
}

export type ProofMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  proofData?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
}

export type ProofMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  proofData?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
}

export type ProofScalarRelationFilter = {
  is?: Prisma.ProofWhereInput
  isNot?: Prisma.ProofWhereInput
}

export type ProofCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutUserInput, Prisma.ProofUncheckedCreateWithoutUserInput> | Prisma.ProofCreateWithoutUserInput[] | Prisma.ProofUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutUserInput | Prisma.ProofCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ProofCreateManyUserInputEnvelope
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
}

export type ProofUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutUserInput, Prisma.ProofUncheckedCreateWithoutUserInput> | Prisma.ProofCreateWithoutUserInput[] | Prisma.ProofUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutUserInput | Prisma.ProofCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ProofCreateManyUserInputEnvelope
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
}

export type ProofUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutUserInput, Prisma.ProofUncheckedCreateWithoutUserInput> | Prisma.ProofCreateWithoutUserInput[] | Prisma.ProofUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutUserInput | Prisma.ProofCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ProofUpsertWithWhereUniqueWithoutUserInput | Prisma.ProofUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ProofCreateManyUserInputEnvelope
  set?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  disconnect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  delete?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  update?: Prisma.ProofUpdateWithWhereUniqueWithoutUserInput | Prisma.ProofUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ProofUpdateManyWithWhereWithoutUserInput | Prisma.ProofUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
}

export type ProofUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutUserInput, Prisma.ProofUncheckedCreateWithoutUserInput> | Prisma.ProofCreateWithoutUserInput[] | Prisma.ProofUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutUserInput | Prisma.ProofCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ProofUpsertWithWhereUniqueWithoutUserInput | Prisma.ProofUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ProofCreateManyUserInputEnvelope
  set?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  disconnect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  delete?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  update?: Prisma.ProofUpdateWithWhereUniqueWithoutUserInput | Prisma.ProofUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ProofUpdateManyWithWhereWithoutUserInput | Prisma.ProofUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
}

export type ProofCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutTaskInput, Prisma.ProofUncheckedCreateWithoutTaskInput> | Prisma.ProofCreateWithoutTaskInput[] | Prisma.ProofUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutTaskInput | Prisma.ProofCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.ProofCreateManyTaskInputEnvelope
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
}

export type ProofUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutTaskInput, Prisma.ProofUncheckedCreateWithoutTaskInput> | Prisma.ProofCreateWithoutTaskInput[] | Prisma.ProofUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutTaskInput | Prisma.ProofCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.ProofCreateManyTaskInputEnvelope
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
}

export type ProofUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutTaskInput, Prisma.ProofUncheckedCreateWithoutTaskInput> | Prisma.ProofCreateWithoutTaskInput[] | Prisma.ProofUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutTaskInput | Prisma.ProofCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.ProofUpsertWithWhereUniqueWithoutTaskInput | Prisma.ProofUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.ProofCreateManyTaskInputEnvelope
  set?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  disconnect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  delete?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  update?: Prisma.ProofUpdateWithWhereUniqueWithoutTaskInput | Prisma.ProofUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.ProofUpdateManyWithWhereWithoutTaskInput | Prisma.ProofUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
}

export type ProofUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutTaskInput, Prisma.ProofUncheckedCreateWithoutTaskInput> | Prisma.ProofCreateWithoutTaskInput[] | Prisma.ProofUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutTaskInput | Prisma.ProofCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.ProofUpsertWithWhereUniqueWithoutTaskInput | Prisma.ProofUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.ProofCreateManyTaskInputEnvelope
  set?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  disconnect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  delete?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  update?: Prisma.ProofUpdateWithWhereUniqueWithoutTaskInput | Prisma.ProofUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.ProofUpdateManyWithWhereWithoutTaskInput | Prisma.ProofUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
}

export type ProofCreateNestedManyWithoutProofTypeInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutProofTypeInput, Prisma.ProofUncheckedCreateWithoutProofTypeInput> | Prisma.ProofCreateWithoutProofTypeInput[] | Prisma.ProofUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutProofTypeInput | Prisma.ProofCreateOrConnectWithoutProofTypeInput[]
  createMany?: Prisma.ProofCreateManyProofTypeInputEnvelope
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
}

export type ProofUncheckedCreateNestedManyWithoutProofTypeInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutProofTypeInput, Prisma.ProofUncheckedCreateWithoutProofTypeInput> | Prisma.ProofCreateWithoutProofTypeInput[] | Prisma.ProofUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutProofTypeInput | Prisma.ProofCreateOrConnectWithoutProofTypeInput[]
  createMany?: Prisma.ProofCreateManyProofTypeInputEnvelope
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
}

export type ProofUpdateManyWithoutProofTypeNestedInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutProofTypeInput, Prisma.ProofUncheckedCreateWithoutProofTypeInput> | Prisma.ProofCreateWithoutProofTypeInput[] | Prisma.ProofUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutProofTypeInput | Prisma.ProofCreateOrConnectWithoutProofTypeInput[]
  upsert?: Prisma.ProofUpsertWithWhereUniqueWithoutProofTypeInput | Prisma.ProofUpsertWithWhereUniqueWithoutProofTypeInput[]
  createMany?: Prisma.ProofCreateManyProofTypeInputEnvelope
  set?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  disconnect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  delete?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  update?: Prisma.ProofUpdateWithWhereUniqueWithoutProofTypeInput | Prisma.ProofUpdateWithWhereUniqueWithoutProofTypeInput[]
  updateMany?: Prisma.ProofUpdateManyWithWhereWithoutProofTypeInput | Prisma.ProofUpdateManyWithWhereWithoutProofTypeInput[]
  deleteMany?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
}

export type ProofUncheckedUpdateManyWithoutProofTypeNestedInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutProofTypeInput, Prisma.ProofUncheckedCreateWithoutProofTypeInput> | Prisma.ProofCreateWithoutProofTypeInput[] | Prisma.ProofUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutProofTypeInput | Prisma.ProofCreateOrConnectWithoutProofTypeInput[]
  upsert?: Prisma.ProofUpsertWithWhereUniqueWithoutProofTypeInput | Prisma.ProofUpsertWithWhereUniqueWithoutProofTypeInput[]
  createMany?: Prisma.ProofCreateManyProofTypeInputEnvelope
  set?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  disconnect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  delete?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  connect?: Prisma.ProofWhereUniqueInput | Prisma.ProofWhereUniqueInput[]
  update?: Prisma.ProofUpdateWithWhereUniqueWithoutProofTypeInput | Prisma.ProofUpdateWithWhereUniqueWithoutProofTypeInput[]
  updateMany?: Prisma.ProofUpdateManyWithWhereWithoutProofTypeInput | Prisma.ProofUpdateManyWithWhereWithoutProofTypeInput[]
  deleteMany?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
}

export type ProofCreateNestedOneWithoutVerificationsInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutVerificationsInput, Prisma.ProofUncheckedCreateWithoutVerificationsInput>
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutVerificationsInput
  connect?: Prisma.ProofWhereUniqueInput
}

export type ProofUpdateOneRequiredWithoutVerificationsNestedInput = {
  create?: Prisma.XOR<Prisma.ProofCreateWithoutVerificationsInput, Prisma.ProofUncheckedCreateWithoutVerificationsInput>
  connectOrCreate?: Prisma.ProofCreateOrConnectWithoutVerificationsInput
  upsert?: Prisma.ProofUpsertWithoutVerificationsInput
  connect?: Prisma.ProofWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProofUpdateToOneWithWhereWithoutVerificationsInput, Prisma.ProofUpdateWithoutVerificationsInput>, Prisma.ProofUncheckedUpdateWithoutVerificationsInput>
}

export type ProofCreateWithoutUserInput = {
  id?: string
  proofData: string
  task: Prisma.TaskCreateNestedOneWithoutProofsInput
  proofType: Prisma.ProofTypeCreateNestedOneWithoutProofsInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutProofInput
}

export type ProofUncheckedCreateWithoutUserInput = {
  id?: string
  proofData: string
  taskId: string
  proofTypeId: string
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutProofInput
}

export type ProofCreateOrConnectWithoutUserInput = {
  where: Prisma.ProofWhereUniqueInput
  create: Prisma.XOR<Prisma.ProofCreateWithoutUserInput, Prisma.ProofUncheckedCreateWithoutUserInput>
}

export type ProofCreateManyUserInputEnvelope = {
  data: Prisma.ProofCreateManyUserInput | Prisma.ProofCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ProofUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ProofWhereUniqueInput
  update: Prisma.XOR<Prisma.ProofUpdateWithoutUserInput, Prisma.ProofUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ProofCreateWithoutUserInput, Prisma.ProofUncheckedCreateWithoutUserInput>
}

export type ProofUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ProofWhereUniqueInput
  data: Prisma.XOR<Prisma.ProofUpdateWithoutUserInput, Prisma.ProofUncheckedUpdateWithoutUserInput>
}

export type ProofUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ProofScalarWhereInput
  data: Prisma.XOR<Prisma.ProofUpdateManyMutationInput, Prisma.ProofUncheckedUpdateManyWithoutUserInput>
}

export type ProofScalarWhereInput = {
  AND?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
  OR?: Prisma.ProofScalarWhereInput[]
  NOT?: Prisma.ProofScalarWhereInput | Prisma.ProofScalarWhereInput[]
  id?: Prisma.StringFilter<"Proof"> | string
  proofData?: Prisma.StringFilter<"Proof"> | string
  taskId?: Prisma.StringFilter<"Proof"> | string
  userId?: Prisma.StringFilter<"Proof"> | string
  proofTypeId?: Prisma.StringFilter<"Proof"> | string
}

export type ProofCreateWithoutTaskInput = {
  id?: string
  proofData: string
  user: Prisma.UserCreateNestedOneWithoutProofsInput
  proofType: Prisma.ProofTypeCreateNestedOneWithoutProofsInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutProofInput
}

export type ProofUncheckedCreateWithoutTaskInput = {
  id?: string
  proofData: string
  userId: string
  proofTypeId: string
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutProofInput
}

export type ProofCreateOrConnectWithoutTaskInput = {
  where: Prisma.ProofWhereUniqueInput
  create: Prisma.XOR<Prisma.ProofCreateWithoutTaskInput, Prisma.ProofUncheckedCreateWithoutTaskInput>
}

export type ProofCreateManyTaskInputEnvelope = {
  data: Prisma.ProofCreateManyTaskInput | Prisma.ProofCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type ProofUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.ProofWhereUniqueInput
  update: Prisma.XOR<Prisma.ProofUpdateWithoutTaskInput, Prisma.ProofUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.ProofCreateWithoutTaskInput, Prisma.ProofUncheckedCreateWithoutTaskInput>
}

export type ProofUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.ProofWhereUniqueInput
  data: Prisma.XOR<Prisma.ProofUpdateWithoutTaskInput, Prisma.ProofUncheckedUpdateWithoutTaskInput>
}

export type ProofUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.ProofScalarWhereInput
  data: Prisma.XOR<Prisma.ProofUpdateManyMutationInput, Prisma.ProofUncheckedUpdateManyWithoutTaskInput>
}

export type ProofCreateWithoutProofTypeInput = {
  id?: string
  proofData: string
  task: Prisma.TaskCreateNestedOneWithoutProofsInput
  user: Prisma.UserCreateNestedOneWithoutProofsInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutProofInput
}

export type ProofUncheckedCreateWithoutProofTypeInput = {
  id?: string
  proofData: string
  taskId: string
  userId: string
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutProofInput
}

export type ProofCreateOrConnectWithoutProofTypeInput = {
  where: Prisma.ProofWhereUniqueInput
  create: Prisma.XOR<Prisma.ProofCreateWithoutProofTypeInput, Prisma.ProofUncheckedCreateWithoutProofTypeInput>
}

export type ProofCreateManyProofTypeInputEnvelope = {
  data: Prisma.ProofCreateManyProofTypeInput | Prisma.ProofCreateManyProofTypeInput[]
  skipDuplicates?: boolean
}

export type ProofUpsertWithWhereUniqueWithoutProofTypeInput = {
  where: Prisma.ProofWhereUniqueInput
  update: Prisma.XOR<Prisma.ProofUpdateWithoutProofTypeInput, Prisma.ProofUncheckedUpdateWithoutProofTypeInput>
  create: Prisma.XOR<Prisma.ProofCreateWithoutProofTypeInput, Prisma.ProofUncheckedCreateWithoutProofTypeInput>
}

export type ProofUpdateWithWhereUniqueWithoutProofTypeInput = {
  where: Prisma.ProofWhereUniqueInput
  data: Prisma.XOR<Prisma.ProofUpdateWithoutProofTypeInput, Prisma.ProofUncheckedUpdateWithoutProofTypeInput>
}

export type ProofUpdateManyWithWhereWithoutProofTypeInput = {
  where: Prisma.ProofScalarWhereInput
  data: Prisma.XOR<Prisma.ProofUpdateManyMutationInput, Prisma.ProofUncheckedUpdateManyWithoutProofTypeInput>
}

export type ProofCreateWithoutVerificationsInput = {
  id?: string
  proofData: string
  task: Prisma.TaskCreateNestedOneWithoutProofsInput
  user: Prisma.UserCreateNestedOneWithoutProofsInput
  proofType: Prisma.ProofTypeCreateNestedOneWithoutProofsInput
}

export type ProofUncheckedCreateWithoutVerificationsInput = {
  id?: string
  proofData: string
  taskId: string
  userId: string
  proofTypeId: string
}

export type ProofCreateOrConnectWithoutVerificationsInput = {
  where: Prisma.ProofWhereUniqueInput
  create: Prisma.XOR<Prisma.ProofCreateWithoutVerificationsInput, Prisma.ProofUncheckedCreateWithoutVerificationsInput>
}

export type ProofUpsertWithoutVerificationsInput = {
  update: Prisma.XOR<Prisma.ProofUpdateWithoutVerificationsInput, Prisma.ProofUncheckedUpdateWithoutVerificationsInput>
  create: Prisma.XOR<Prisma.ProofCreateWithoutVerificationsInput, Prisma.ProofUncheckedCreateWithoutVerificationsInput>
  where?: Prisma.ProofWhereInput
}

export type ProofUpdateToOneWithWhereWithoutVerificationsInput = {
  where?: Prisma.ProofWhereInput
  data: Prisma.XOR<Prisma.ProofUpdateWithoutVerificationsInput, Prisma.ProofUncheckedUpdateWithoutVerificationsInput>
}

export type ProofUpdateWithoutVerificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.TaskUpdateOneRequiredWithoutProofsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutProofsNestedInput
  proofType?: Prisma.ProofTypeUpdateOneRequiredWithoutProofsNestedInput
}

export type ProofUncheckedUpdateWithoutVerificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProofCreateManyUserInput = {
  id?: string
  proofData: string
  taskId: string
  proofTypeId: string
}

export type ProofUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.TaskUpdateOneRequiredWithoutProofsNestedInput
  proofType?: Prisma.ProofTypeUpdateOneRequiredWithoutProofsNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutProofNestedInput
}

export type ProofUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutProofNestedInput
}

export type ProofUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProofCreateManyTaskInput = {
  id?: string
  proofData: string
  userId: string
  proofTypeId: string
}

export type ProofUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutProofsNestedInput
  proofType?: Prisma.ProofTypeUpdateOneRequiredWithoutProofsNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutProofNestedInput
}

export type ProofUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutProofNestedInput
}

export type ProofUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ProofCreateManyProofTypeInput = {
  id?: string
  proofData: string
  taskId: string
  userId: string
}

export type ProofUpdateWithoutProofTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  task?: Prisma.TaskUpdateOneRequiredWithoutProofsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutProofsNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutProofNestedInput
}

export type ProofUncheckedUpdateWithoutProofTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutProofNestedInput
}

export type ProofUncheckedUpdateManyWithoutProofTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofData?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ProofCountOutputType
 */

export type ProofCountOutputType = {
  verifications: number
}

export type ProofCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  verifications?: boolean | ProofCountOutputTypeCountVerificationsArgs
}

/**
 * ProofCountOutputType without action
 */
export type ProofCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProofCountOutputType
   */
  select?: Prisma.ProofCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProofCountOutputType without action
 */
export type ProofCountOutputTypeCountVerificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VerificationWhereInput
}


export type ProofSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  proofData?: boolean
  taskId?: boolean
  userId?: boolean
  proofTypeId?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
  verifications?: boolean | Prisma.Proof$verificationsArgs<ExtArgs>
  _count?: boolean | Prisma.ProofCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proof"]>

export type ProofSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  proofData?: boolean
  taskId?: boolean
  userId?: boolean
  proofTypeId?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proof"]>

export type ProofSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  proofData?: boolean
  taskId?: boolean
  userId?: boolean
  proofTypeId?: boolean
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proof"]>

export type ProofSelectScalar = {
  id?: boolean
  proofData?: boolean
  taskId?: boolean
  userId?: boolean
  proofTypeId?: boolean
}

export type ProofOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "proofData" | "taskId" | "userId" | "proofTypeId", ExtArgs["result"]["proof"]>
export type ProofInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
  verifications?: boolean | Prisma.Proof$verificationsArgs<ExtArgs>
  _count?: boolean | Prisma.ProofCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProofIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}
export type ProofIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}

export type $ProofPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Proof"
  objects: {
    task: Prisma.$TaskPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    proofType: Prisma.$ProofTypePayload<ExtArgs>
    verifications: Prisma.$VerificationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    proofData: string
    taskId: string
    userId: string
    proofTypeId: string
  }, ExtArgs["result"]["proof"]>
  composites: {}
}

export type ProofGetPayload<S extends boolean | null | undefined | ProofDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProofPayload, S>

export type ProofCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProofFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProofCountAggregateInputType | true
  }

export interface ProofDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Proof'], meta: { name: 'Proof' } }
  /**
   * Find zero or one Proof that matches the filter.
   * @param {ProofFindUniqueArgs} args - Arguments to find a Proof
   * @example
   * // Get one Proof
   * const proof = await prisma.proof.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProofFindUniqueArgs>(args: Prisma.SelectSubset<T, ProofFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Proof that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProofFindUniqueOrThrowArgs} args - Arguments to find a Proof
   * @example
   * // Get one Proof
   * const proof = await prisma.proof.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProofFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProofFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proof that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofFindFirstArgs} args - Arguments to find a Proof
   * @example
   * // Get one Proof
   * const proof = await prisma.proof.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProofFindFirstArgs>(args?: Prisma.SelectSubset<T, ProofFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proof that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofFindFirstOrThrowArgs} args - Arguments to find a Proof
   * @example
   * // Get one Proof
   * const proof = await prisma.proof.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProofFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProofFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Proofs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Proofs
   * const proofs = await prisma.proof.findMany()
   * 
   * // Get first 10 Proofs
   * const proofs = await prisma.proof.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const proofWithIdOnly = await prisma.proof.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProofFindManyArgs>(args?: Prisma.SelectSubset<T, ProofFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Proof.
   * @param {ProofCreateArgs} args - Arguments to create a Proof.
   * @example
   * // Create one Proof
   * const Proof = await prisma.proof.create({
   *   data: {
   *     // ... data to create a Proof
   *   }
   * })
   * 
   */
  create<T extends ProofCreateArgs>(args: Prisma.SelectSubset<T, ProofCreateArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Proofs.
   * @param {ProofCreateManyArgs} args - Arguments to create many Proofs.
   * @example
   * // Create many Proofs
   * const proof = await prisma.proof.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProofCreateManyArgs>(args?: Prisma.SelectSubset<T, ProofCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Proofs and returns the data saved in the database.
   * @param {ProofCreateManyAndReturnArgs} args - Arguments to create many Proofs.
   * @example
   * // Create many Proofs
   * const proof = await prisma.proof.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Proofs and only return the `id`
   * const proofWithIdOnly = await prisma.proof.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProofCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProofCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Proof.
   * @param {ProofDeleteArgs} args - Arguments to delete one Proof.
   * @example
   * // Delete one Proof
   * const Proof = await prisma.proof.delete({
   *   where: {
   *     // ... filter to delete one Proof
   *   }
   * })
   * 
   */
  delete<T extends ProofDeleteArgs>(args: Prisma.SelectSubset<T, ProofDeleteArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Proof.
   * @param {ProofUpdateArgs} args - Arguments to update one Proof.
   * @example
   * // Update one Proof
   * const proof = await prisma.proof.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProofUpdateArgs>(args: Prisma.SelectSubset<T, ProofUpdateArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Proofs.
   * @param {ProofDeleteManyArgs} args - Arguments to filter Proofs to delete.
   * @example
   * // Delete a few Proofs
   * const { count } = await prisma.proof.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProofDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProofDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proofs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Proofs
   * const proof = await prisma.proof.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProofUpdateManyArgs>(args: Prisma.SelectSubset<T, ProofUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proofs and returns the data updated in the database.
   * @param {ProofUpdateManyAndReturnArgs} args - Arguments to update many Proofs.
   * @example
   * // Update many Proofs
   * const proof = await prisma.proof.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Proofs and only return the `id`
   * const proofWithIdOnly = await prisma.proof.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProofUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProofUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Proof.
   * @param {ProofUpsertArgs} args - Arguments to update or create a Proof.
   * @example
   * // Update or create a Proof
   * const proof = await prisma.proof.upsert({
   *   create: {
   *     // ... data to create a Proof
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Proof we want to update
   *   }
   * })
   */
  upsert<T extends ProofUpsertArgs>(args: Prisma.SelectSubset<T, ProofUpsertArgs<ExtArgs>>): Prisma.Prisma__ProofClient<runtime.Types.Result.GetResult<Prisma.$ProofPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Proofs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofCountArgs} args - Arguments to filter Proofs to count.
   * @example
   * // Count the number of Proofs
   * const count = await prisma.proof.count({
   *   where: {
   *     // ... the filter for the Proofs we want to count
   *   }
   * })
  **/
  count<T extends ProofCountArgs>(
    args?: Prisma.Subset<T, ProofCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProofCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Proof.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProofAggregateArgs>(args: Prisma.Subset<T, ProofAggregateArgs>): Prisma.PrismaPromise<GetProofAggregateType<T>>

  /**
   * Group by Proof.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProofGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProofGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProofGroupByArgs['orderBy'] }
      : { orderBy?: ProofGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProofGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProofGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Proof model
 */
readonly fields: ProofFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Proof.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProofClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  proofType<T extends Prisma.ProofTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProofTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  verifications<T extends Prisma.Proof$verificationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proof$verificationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Proof model
 */
export interface ProofFieldRefs {
  readonly id: Prisma.FieldRef<"Proof", 'String'>
  readonly proofData: Prisma.FieldRef<"Proof", 'String'>
  readonly taskId: Prisma.FieldRef<"Proof", 'String'>
  readonly userId: Prisma.FieldRef<"Proof", 'String'>
  readonly proofTypeId: Prisma.FieldRef<"Proof", 'String'>
}
    

// Custom InputTypes
/**
 * Proof findUnique
 */
export type ProofFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * Filter, which Proof to fetch.
   */
  where: Prisma.ProofWhereUniqueInput
}

/**
 * Proof findUniqueOrThrow
 */
export type ProofFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * Filter, which Proof to fetch.
   */
  where: Prisma.ProofWhereUniqueInput
}

/**
 * Proof findFirst
 */
export type ProofFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * Filter, which Proof to fetch.
   */
  where?: Prisma.ProofWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proofs to fetch.
   */
  orderBy?: Prisma.ProofOrderByWithRelationInput | Prisma.ProofOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proofs.
   */
  cursor?: Prisma.ProofWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proofs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proofs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proofs.
   */
  distinct?: Prisma.ProofScalarFieldEnum | Prisma.ProofScalarFieldEnum[]
}

/**
 * Proof findFirstOrThrow
 */
export type ProofFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * Filter, which Proof to fetch.
   */
  where?: Prisma.ProofWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proofs to fetch.
   */
  orderBy?: Prisma.ProofOrderByWithRelationInput | Prisma.ProofOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proofs.
   */
  cursor?: Prisma.ProofWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proofs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proofs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proofs.
   */
  distinct?: Prisma.ProofScalarFieldEnum | Prisma.ProofScalarFieldEnum[]
}

/**
 * Proof findMany
 */
export type ProofFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * Filter, which Proofs to fetch.
   */
  where?: Prisma.ProofWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proofs to fetch.
   */
  orderBy?: Prisma.ProofOrderByWithRelationInput | Prisma.ProofOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Proofs.
   */
  cursor?: Prisma.ProofWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proofs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proofs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proofs.
   */
  distinct?: Prisma.ProofScalarFieldEnum | Prisma.ProofScalarFieldEnum[]
}

/**
 * Proof create
 */
export type ProofCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * The data needed to create a Proof.
   */
  data: Prisma.XOR<Prisma.ProofCreateInput, Prisma.ProofUncheckedCreateInput>
}

/**
 * Proof createMany
 */
export type ProofCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Proofs.
   */
  data: Prisma.ProofCreateManyInput | Prisma.ProofCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Proof createManyAndReturn
 */
export type ProofCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * The data used to create many Proofs.
   */
  data: Prisma.ProofCreateManyInput | Prisma.ProofCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Proof update
 */
export type ProofUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * The data needed to update a Proof.
   */
  data: Prisma.XOR<Prisma.ProofUpdateInput, Prisma.ProofUncheckedUpdateInput>
  /**
   * Choose, which Proof to update.
   */
  where: Prisma.ProofWhereUniqueInput
}

/**
 * Proof updateMany
 */
export type ProofUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Proofs.
   */
  data: Prisma.XOR<Prisma.ProofUpdateManyMutationInput, Prisma.ProofUncheckedUpdateManyInput>
  /**
   * Filter which Proofs to update
   */
  where?: Prisma.ProofWhereInput
  /**
   * Limit how many Proofs to update.
   */
  limit?: number
}

/**
 * Proof updateManyAndReturn
 */
export type ProofUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * The data used to update Proofs.
   */
  data: Prisma.XOR<Prisma.ProofUpdateManyMutationInput, Prisma.ProofUncheckedUpdateManyInput>
  /**
   * Filter which Proofs to update
   */
  where?: Prisma.ProofWhereInput
  /**
   * Limit how many Proofs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Proof upsert
 */
export type ProofUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * The filter to search for the Proof to update in case it exists.
   */
  where: Prisma.ProofWhereUniqueInput
  /**
   * In case the Proof found by the `where` argument doesn't exist, create a new Proof with this data.
   */
  create: Prisma.XOR<Prisma.ProofCreateInput, Prisma.ProofUncheckedCreateInput>
  /**
   * In case the Proof was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProofUpdateInput, Prisma.ProofUncheckedUpdateInput>
}

/**
 * Proof delete
 */
export type ProofDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
  /**
   * Filter which Proof to delete.
   */
  where: Prisma.ProofWhereUniqueInput
}

/**
 * Proof deleteMany
 */
export type ProofDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proofs to delete
   */
  where?: Prisma.ProofWhereInput
  /**
   * Limit how many Proofs to delete.
   */
  limit?: number
}

/**
 * Proof.verifications
 */
export type Proof$verificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verification
   */
  select?: Prisma.VerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verification
   */
  omit?: Prisma.VerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerificationInclude<ExtArgs> | null
  where?: Prisma.VerificationWhereInput
  orderBy?: Prisma.VerificationOrderByWithRelationInput | Prisma.VerificationOrderByWithRelationInput[]
  cursor?: Prisma.VerificationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VerificationScalarFieldEnum | Prisma.VerificationScalarFieldEnum[]
}

/**
 * Proof without action
 */
export type ProofDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proof
   */
  select?: Prisma.ProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proof
   */
  omit?: Prisma.ProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProofInclude<ExtArgs> | null
}
