
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TaskSessions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TaskSessions
 * 
 */
export type TaskSessionsModel = runtime.Types.Result.DefaultSelection<Prisma.$TaskSessionsPayload>

export type AggregateTaskSessions = {
  _count: TaskSessionsCountAggregateOutputType | null
  _min: TaskSessionsMinAggregateOutputType | null
  _max: TaskSessionsMaxAggregateOutputType | null
}

export type TaskSessionsMinAggregateOutputType = {
  id: string | null
  focusSessionId: string | null
  taskId: string | null
  assignedAt: Date | null
}

export type TaskSessionsMaxAggregateOutputType = {
  id: string | null
  focusSessionId: string | null
  taskId: string | null
  assignedAt: Date | null
}

export type TaskSessionsCountAggregateOutputType = {
  id: number
  focusSessionId: number
  taskId: number
  assignedAt: number
  _all: number
}


export type TaskSessionsMinAggregateInputType = {
  id?: true
  focusSessionId?: true
  taskId?: true
  assignedAt?: true
}

export type TaskSessionsMaxAggregateInputType = {
  id?: true
  focusSessionId?: true
  taskId?: true
  assignedAt?: true
}

export type TaskSessionsCountAggregateInputType = {
  id?: true
  focusSessionId?: true
  taskId?: true
  assignedAt?: true
  _all?: true
}

export type TaskSessionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaskSessions to aggregate.
   */
  where?: Prisma.TaskSessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskSessions to fetch.
   */
  orderBy?: Prisma.TaskSessionsOrderByWithRelationInput | Prisma.TaskSessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaskSessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TaskSessions
  **/
  _count?: true | TaskSessionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaskSessionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaskSessionsMaxAggregateInputType
}

export type GetTaskSessionsAggregateType<T extends TaskSessionsAggregateArgs> = {
      [P in keyof T & keyof AggregateTaskSessions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaskSessions[P]>
    : Prisma.GetScalarType<T[P], AggregateTaskSessions[P]>
}




export type TaskSessionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskSessionsWhereInput
  orderBy?: Prisma.TaskSessionsOrderByWithAggregationInput | Prisma.TaskSessionsOrderByWithAggregationInput[]
  by: Prisma.TaskSessionsScalarFieldEnum[] | Prisma.TaskSessionsScalarFieldEnum
  having?: Prisma.TaskSessionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaskSessionsCountAggregateInputType | true
  _min?: TaskSessionsMinAggregateInputType
  _max?: TaskSessionsMaxAggregateInputType
}

export type TaskSessionsGroupByOutputType = {
  id: string
  focusSessionId: string
  taskId: string
  assignedAt: Date
  _count: TaskSessionsCountAggregateOutputType | null
  _min: TaskSessionsMinAggregateOutputType | null
  _max: TaskSessionsMaxAggregateOutputType | null
}

export type GetTaskSessionsGroupByPayload<T extends TaskSessionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaskSessionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaskSessionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaskSessionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaskSessionsGroupByOutputType[P]>
      }
    >
  >



export type TaskSessionsWhereInput = {
  AND?: Prisma.TaskSessionsWhereInput | Prisma.TaskSessionsWhereInput[]
  OR?: Prisma.TaskSessionsWhereInput[]
  NOT?: Prisma.TaskSessionsWhereInput | Prisma.TaskSessionsWhereInput[]
  id?: Prisma.StringFilter<"TaskSessions"> | string
  focusSessionId?: Prisma.StringFilter<"TaskSessions"> | string
  taskId?: Prisma.StringFilter<"TaskSessions"> | string
  assignedAt?: Prisma.DateTimeFilter<"TaskSessions"> | Date | string
  focusSession?: Prisma.XOR<Prisma.FocusSessionScalarRelationFilter, Prisma.FocusSessionWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}

export type TaskSessionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  focusSession?: Prisma.FocusSessionOrderByWithRelationInput
  task?: Prisma.TaskOrderByWithRelationInput
}

export type TaskSessionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  focusSessionId_taskId?: Prisma.TaskSessionsFocusSessionIdTaskIdCompoundUniqueInput
  AND?: Prisma.TaskSessionsWhereInput | Prisma.TaskSessionsWhereInput[]
  OR?: Prisma.TaskSessionsWhereInput[]
  NOT?: Prisma.TaskSessionsWhereInput | Prisma.TaskSessionsWhereInput[]
  focusSessionId?: Prisma.StringFilter<"TaskSessions"> | string
  taskId?: Prisma.StringFilter<"TaskSessions"> | string
  assignedAt?: Prisma.DateTimeFilter<"TaskSessions"> | Date | string
  focusSession?: Prisma.XOR<Prisma.FocusSessionScalarRelationFilter, Prisma.FocusSessionWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}, "id" | "focusSessionId_taskId">

export type TaskSessionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  _count?: Prisma.TaskSessionsCountOrderByAggregateInput
  _max?: Prisma.TaskSessionsMaxOrderByAggregateInput
  _min?: Prisma.TaskSessionsMinOrderByAggregateInput
}

export type TaskSessionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaskSessionsScalarWhereWithAggregatesInput | Prisma.TaskSessionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaskSessionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaskSessionsScalarWhereWithAggregatesInput | Prisma.TaskSessionsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TaskSessions"> | string
  focusSessionId?: Prisma.StringWithAggregatesFilter<"TaskSessions"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"TaskSessions"> | string
  assignedAt?: Prisma.DateTimeWithAggregatesFilter<"TaskSessions"> | Date | string
}

export type TaskSessionsCreateInput = {
  id?: string
  assignedAt?: Date | string
  focusSession: Prisma.FocusSessionCreateNestedOneWithoutTasksInput
  task: Prisma.TaskCreateNestedOneWithoutTaskSessionsInput
}

export type TaskSessionsUncheckedCreateInput = {
  id?: string
  focusSessionId: string
  taskId: string
  assignedAt?: Date | string
}

export type TaskSessionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  focusSession?: Prisma.FocusSessionUpdateOneRequiredWithoutTasksNestedInput
  task?: Prisma.TaskUpdateOneRequiredWithoutTaskSessionsNestedInput
}

export type TaskSessionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaskSessionsCreateManyInput = {
  id?: string
  focusSessionId: string
  taskId: string
  assignedAt?: Date | string
}

export type TaskSessionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaskSessionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaskSessionsListRelationFilter = {
  every?: Prisma.TaskSessionsWhereInput
  some?: Prisma.TaskSessionsWhereInput
  none?: Prisma.TaskSessionsWhereInput
}

export type TaskSessionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TaskSessionsFocusSessionIdTaskIdCompoundUniqueInput = {
  focusSessionId: string
  taskId: string
}

export type TaskSessionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type TaskSessionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type TaskSessionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  focusSessionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type TaskSessionsCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutTaskInput, Prisma.TaskSessionsUncheckedCreateWithoutTaskInput> | Prisma.TaskSessionsCreateWithoutTaskInput[] | Prisma.TaskSessionsUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutTaskInput | Prisma.TaskSessionsCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TaskSessionsCreateManyTaskInputEnvelope
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
}

export type TaskSessionsUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutTaskInput, Prisma.TaskSessionsUncheckedCreateWithoutTaskInput> | Prisma.TaskSessionsCreateWithoutTaskInput[] | Prisma.TaskSessionsUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutTaskInput | Prisma.TaskSessionsCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TaskSessionsCreateManyTaskInputEnvelope
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
}

export type TaskSessionsUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutTaskInput, Prisma.TaskSessionsUncheckedCreateWithoutTaskInput> | Prisma.TaskSessionsCreateWithoutTaskInput[] | Prisma.TaskSessionsUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutTaskInput | Prisma.TaskSessionsCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TaskSessionsUpsertWithWhereUniqueWithoutTaskInput | Prisma.TaskSessionsUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TaskSessionsCreateManyTaskInputEnvelope
  set?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  disconnect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  delete?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  update?: Prisma.TaskSessionsUpdateWithWhereUniqueWithoutTaskInput | Prisma.TaskSessionsUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TaskSessionsUpdateManyWithWhereWithoutTaskInput | Prisma.TaskSessionsUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TaskSessionsScalarWhereInput | Prisma.TaskSessionsScalarWhereInput[]
}

export type TaskSessionsUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutTaskInput, Prisma.TaskSessionsUncheckedCreateWithoutTaskInput> | Prisma.TaskSessionsCreateWithoutTaskInput[] | Prisma.TaskSessionsUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutTaskInput | Prisma.TaskSessionsCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TaskSessionsUpsertWithWhereUniqueWithoutTaskInput | Prisma.TaskSessionsUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TaskSessionsCreateManyTaskInputEnvelope
  set?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  disconnect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  delete?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  update?: Prisma.TaskSessionsUpdateWithWhereUniqueWithoutTaskInput | Prisma.TaskSessionsUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TaskSessionsUpdateManyWithWhereWithoutTaskInput | Prisma.TaskSessionsUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TaskSessionsScalarWhereInput | Prisma.TaskSessionsScalarWhereInput[]
}

export type TaskSessionsCreateNestedManyWithoutFocusSessionInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput> | Prisma.TaskSessionsCreateWithoutFocusSessionInput[] | Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput | Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput[]
  createMany?: Prisma.TaskSessionsCreateManyFocusSessionInputEnvelope
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
}

export type TaskSessionsUncheckedCreateNestedManyWithoutFocusSessionInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput> | Prisma.TaskSessionsCreateWithoutFocusSessionInput[] | Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput | Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput[]
  createMany?: Prisma.TaskSessionsCreateManyFocusSessionInputEnvelope
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
}

export type TaskSessionsUpdateManyWithoutFocusSessionNestedInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput> | Prisma.TaskSessionsCreateWithoutFocusSessionInput[] | Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput | Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput[]
  upsert?: Prisma.TaskSessionsUpsertWithWhereUniqueWithoutFocusSessionInput | Prisma.TaskSessionsUpsertWithWhereUniqueWithoutFocusSessionInput[]
  createMany?: Prisma.TaskSessionsCreateManyFocusSessionInputEnvelope
  set?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  disconnect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  delete?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  update?: Prisma.TaskSessionsUpdateWithWhereUniqueWithoutFocusSessionInput | Prisma.TaskSessionsUpdateWithWhereUniqueWithoutFocusSessionInput[]
  updateMany?: Prisma.TaskSessionsUpdateManyWithWhereWithoutFocusSessionInput | Prisma.TaskSessionsUpdateManyWithWhereWithoutFocusSessionInput[]
  deleteMany?: Prisma.TaskSessionsScalarWhereInput | Prisma.TaskSessionsScalarWhereInput[]
}

export type TaskSessionsUncheckedUpdateManyWithoutFocusSessionNestedInput = {
  create?: Prisma.XOR<Prisma.TaskSessionsCreateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput> | Prisma.TaskSessionsCreateWithoutFocusSessionInput[] | Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput[]
  connectOrCreate?: Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput | Prisma.TaskSessionsCreateOrConnectWithoutFocusSessionInput[]
  upsert?: Prisma.TaskSessionsUpsertWithWhereUniqueWithoutFocusSessionInput | Prisma.TaskSessionsUpsertWithWhereUniqueWithoutFocusSessionInput[]
  createMany?: Prisma.TaskSessionsCreateManyFocusSessionInputEnvelope
  set?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  disconnect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  delete?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  connect?: Prisma.TaskSessionsWhereUniqueInput | Prisma.TaskSessionsWhereUniqueInput[]
  update?: Prisma.TaskSessionsUpdateWithWhereUniqueWithoutFocusSessionInput | Prisma.TaskSessionsUpdateWithWhereUniqueWithoutFocusSessionInput[]
  updateMany?: Prisma.TaskSessionsUpdateManyWithWhereWithoutFocusSessionInput | Prisma.TaskSessionsUpdateManyWithWhereWithoutFocusSessionInput[]
  deleteMany?: Prisma.TaskSessionsScalarWhereInput | Prisma.TaskSessionsScalarWhereInput[]
}

export type TaskSessionsCreateWithoutTaskInput = {
  id?: string
  assignedAt?: Date | string
  focusSession: Prisma.FocusSessionCreateNestedOneWithoutTasksInput
}

export type TaskSessionsUncheckedCreateWithoutTaskInput = {
  id?: string
  focusSessionId: string
  assignedAt?: Date | string
}

export type TaskSessionsCreateOrConnectWithoutTaskInput = {
  where: Prisma.TaskSessionsWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskSessionsCreateWithoutTaskInput, Prisma.TaskSessionsUncheckedCreateWithoutTaskInput>
}

export type TaskSessionsCreateManyTaskInputEnvelope = {
  data: Prisma.TaskSessionsCreateManyTaskInput | Prisma.TaskSessionsCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type TaskSessionsUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TaskSessionsWhereUniqueInput
  update: Prisma.XOR<Prisma.TaskSessionsUpdateWithoutTaskInput, Prisma.TaskSessionsUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.TaskSessionsCreateWithoutTaskInput, Prisma.TaskSessionsUncheckedCreateWithoutTaskInput>
}

export type TaskSessionsUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TaskSessionsWhereUniqueInput
  data: Prisma.XOR<Prisma.TaskSessionsUpdateWithoutTaskInput, Prisma.TaskSessionsUncheckedUpdateWithoutTaskInput>
}

export type TaskSessionsUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.TaskSessionsScalarWhereInput
  data: Prisma.XOR<Prisma.TaskSessionsUpdateManyMutationInput, Prisma.TaskSessionsUncheckedUpdateManyWithoutTaskInput>
}

export type TaskSessionsScalarWhereInput = {
  AND?: Prisma.TaskSessionsScalarWhereInput | Prisma.TaskSessionsScalarWhereInput[]
  OR?: Prisma.TaskSessionsScalarWhereInput[]
  NOT?: Prisma.TaskSessionsScalarWhereInput | Prisma.TaskSessionsScalarWhereInput[]
  id?: Prisma.StringFilter<"TaskSessions"> | string
  focusSessionId?: Prisma.StringFilter<"TaskSessions"> | string
  taskId?: Prisma.StringFilter<"TaskSessions"> | string
  assignedAt?: Prisma.DateTimeFilter<"TaskSessions"> | Date | string
}

export type TaskSessionsCreateWithoutFocusSessionInput = {
  id?: string
  assignedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutTaskSessionsInput
}

export type TaskSessionsUncheckedCreateWithoutFocusSessionInput = {
  id?: string
  taskId: string
  assignedAt?: Date | string
}

export type TaskSessionsCreateOrConnectWithoutFocusSessionInput = {
  where: Prisma.TaskSessionsWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskSessionsCreateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput>
}

export type TaskSessionsCreateManyFocusSessionInputEnvelope = {
  data: Prisma.TaskSessionsCreateManyFocusSessionInput | Prisma.TaskSessionsCreateManyFocusSessionInput[]
  skipDuplicates?: boolean
}

export type TaskSessionsUpsertWithWhereUniqueWithoutFocusSessionInput = {
  where: Prisma.TaskSessionsWhereUniqueInput
  update: Prisma.XOR<Prisma.TaskSessionsUpdateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedUpdateWithoutFocusSessionInput>
  create: Prisma.XOR<Prisma.TaskSessionsCreateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedCreateWithoutFocusSessionInput>
}

export type TaskSessionsUpdateWithWhereUniqueWithoutFocusSessionInput = {
  where: Prisma.TaskSessionsWhereUniqueInput
  data: Prisma.XOR<Prisma.TaskSessionsUpdateWithoutFocusSessionInput, Prisma.TaskSessionsUncheckedUpdateWithoutFocusSessionInput>
}

export type TaskSessionsUpdateManyWithWhereWithoutFocusSessionInput = {
  where: Prisma.TaskSessionsScalarWhereInput
  data: Prisma.XOR<Prisma.TaskSessionsUpdateManyMutationInput, Prisma.TaskSessionsUncheckedUpdateManyWithoutFocusSessionInput>
}

export type TaskSessionsCreateManyTaskInput = {
  id?: string
  focusSessionId: string
  assignedAt?: Date | string
}

export type TaskSessionsUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  focusSession?: Prisma.FocusSessionUpdateOneRequiredWithoutTasksNestedInput
}

export type TaskSessionsUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaskSessionsUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  focusSessionId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaskSessionsCreateManyFocusSessionInput = {
  id?: string
  taskId: string
  assignedAt?: Date | string
}

export type TaskSessionsUpdateWithoutFocusSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutTaskSessionsNestedInput
}

export type TaskSessionsUncheckedUpdateWithoutFocusSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaskSessionsUncheckedUpdateManyWithoutFocusSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TaskSessionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskSessions"]>

export type TaskSessionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskSessions"]>

export type TaskSessionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskSessions"]>

export type TaskSessionsSelectScalar = {
  id?: boolean
  focusSessionId?: boolean
  taskId?: boolean
  assignedAt?: boolean
}

export type TaskSessionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "focusSessionId" | "taskId" | "assignedAt", ExtArgs["result"]["taskSessions"]>
export type TaskSessionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type TaskSessionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type TaskSessionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  focusSession?: boolean | Prisma.FocusSessionDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}

export type $TaskSessionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TaskSessions"
  objects: {
    focusSession: Prisma.$FocusSessionPayload<ExtArgs>
    task: Prisma.$TaskPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    focusSessionId: string
    taskId: string
    assignedAt: Date
  }, ExtArgs["result"]["taskSessions"]>
  composites: {}
}

export type TaskSessionsGetPayload<S extends boolean | null | undefined | TaskSessionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload, S>

export type TaskSessionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaskSessionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TaskSessionsCountAggregateInputType | true
  }

export interface TaskSessionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TaskSessions'], meta: { name: 'TaskSessions' } }
  /**
   * Find zero or one TaskSessions that matches the filter.
   * @param {TaskSessionsFindUniqueArgs} args - Arguments to find a TaskSessions
   * @example
   * // Get one TaskSessions
   * const taskSessions = await prisma.taskSessions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaskSessionsFindUniqueArgs>(args: Prisma.SelectSubset<T, TaskSessionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TaskSessions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaskSessionsFindUniqueOrThrowArgs} args - Arguments to find a TaskSessions
   * @example
   * // Get one TaskSessions
   * const taskSessions = await prisma.taskSessions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaskSessionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaskSessionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaskSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskSessionsFindFirstArgs} args - Arguments to find a TaskSessions
   * @example
   * // Get one TaskSessions
   * const taskSessions = await prisma.taskSessions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaskSessionsFindFirstArgs>(args?: Prisma.SelectSubset<T, TaskSessionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaskSessions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskSessionsFindFirstOrThrowArgs} args - Arguments to find a TaskSessions
   * @example
   * // Get one TaskSessions
   * const taskSessions = await prisma.taskSessions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaskSessionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaskSessionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TaskSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskSessionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TaskSessions
   * const taskSessions = await prisma.taskSessions.findMany()
   * 
   * // Get first 10 TaskSessions
   * const taskSessions = await prisma.taskSessions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taskSessionsWithIdOnly = await prisma.taskSessions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaskSessionsFindManyArgs>(args?: Prisma.SelectSubset<T, TaskSessionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TaskSessions.
   * @param {TaskSessionsCreateArgs} args - Arguments to create a TaskSessions.
   * @example
   * // Create one TaskSessions
   * const TaskSessions = await prisma.taskSessions.create({
   *   data: {
   *     // ... data to create a TaskSessions
   *   }
   * })
   * 
   */
  create<T extends TaskSessionsCreateArgs>(args: Prisma.SelectSubset<T, TaskSessionsCreateArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TaskSessions.
   * @param {TaskSessionsCreateManyArgs} args - Arguments to create many TaskSessions.
   * @example
   * // Create many TaskSessions
   * const taskSessions = await prisma.taskSessions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaskSessionsCreateManyArgs>(args?: Prisma.SelectSubset<T, TaskSessionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TaskSessions and returns the data saved in the database.
   * @param {TaskSessionsCreateManyAndReturnArgs} args - Arguments to create many TaskSessions.
   * @example
   * // Create many TaskSessions
   * const taskSessions = await prisma.taskSessions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TaskSessions and only return the `id`
   * const taskSessionsWithIdOnly = await prisma.taskSessions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaskSessionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaskSessionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TaskSessions.
   * @param {TaskSessionsDeleteArgs} args - Arguments to delete one TaskSessions.
   * @example
   * // Delete one TaskSessions
   * const TaskSessions = await prisma.taskSessions.delete({
   *   where: {
   *     // ... filter to delete one TaskSessions
   *   }
   * })
   * 
   */
  delete<T extends TaskSessionsDeleteArgs>(args: Prisma.SelectSubset<T, TaskSessionsDeleteArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TaskSessions.
   * @param {TaskSessionsUpdateArgs} args - Arguments to update one TaskSessions.
   * @example
   * // Update one TaskSessions
   * const taskSessions = await prisma.taskSessions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaskSessionsUpdateArgs>(args: Prisma.SelectSubset<T, TaskSessionsUpdateArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TaskSessions.
   * @param {TaskSessionsDeleteManyArgs} args - Arguments to filter TaskSessions to delete.
   * @example
   * // Delete a few TaskSessions
   * const { count } = await prisma.taskSessions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaskSessionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaskSessionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaskSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskSessionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TaskSessions
   * const taskSessions = await prisma.taskSessions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaskSessionsUpdateManyArgs>(args: Prisma.SelectSubset<T, TaskSessionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaskSessions and returns the data updated in the database.
   * @param {TaskSessionsUpdateManyAndReturnArgs} args - Arguments to update many TaskSessions.
   * @example
   * // Update many TaskSessions
   * const taskSessions = await prisma.taskSessions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TaskSessions and only return the `id`
   * const taskSessionsWithIdOnly = await prisma.taskSessions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaskSessionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaskSessionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TaskSessions.
   * @param {TaskSessionsUpsertArgs} args - Arguments to update or create a TaskSessions.
   * @example
   * // Update or create a TaskSessions
   * const taskSessions = await prisma.taskSessions.upsert({
   *   create: {
   *     // ... data to create a TaskSessions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TaskSessions we want to update
   *   }
   * })
   */
  upsert<T extends TaskSessionsUpsertArgs>(args: Prisma.SelectSubset<T, TaskSessionsUpsertArgs<ExtArgs>>): Prisma.Prisma__TaskSessionsClient<runtime.Types.Result.GetResult<Prisma.$TaskSessionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TaskSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskSessionsCountArgs} args - Arguments to filter TaskSessions to count.
   * @example
   * // Count the number of TaskSessions
   * const count = await prisma.taskSessions.count({
   *   where: {
   *     // ... the filter for the TaskSessions we want to count
   *   }
   * })
  **/
  count<T extends TaskSessionsCountArgs>(
    args?: Prisma.Subset<T, TaskSessionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaskSessionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TaskSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskSessionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaskSessionsAggregateArgs>(args: Prisma.Subset<T, TaskSessionsAggregateArgs>): Prisma.PrismaPromise<GetTaskSessionsAggregateType<T>>

  /**
   * Group by TaskSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskSessionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaskSessionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaskSessionsGroupByArgs['orderBy'] }
      : { orderBy?: TaskSessionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaskSessionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaskSessionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TaskSessions model
 */
readonly fields: TaskSessionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TaskSessions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaskSessionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  focusSession<T extends Prisma.FocusSessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FocusSessionDefaultArgs<ExtArgs>>): Prisma.Prisma__FocusSessionClient<runtime.Types.Result.GetResult<Prisma.$FocusSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TaskSessions model
 */
export interface TaskSessionsFieldRefs {
  readonly id: Prisma.FieldRef<"TaskSessions", 'String'>
  readonly focusSessionId: Prisma.FieldRef<"TaskSessions", 'String'>
  readonly taskId: Prisma.FieldRef<"TaskSessions", 'String'>
  readonly assignedAt: Prisma.FieldRef<"TaskSessions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TaskSessions findUnique
 */
export type TaskSessionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * Filter, which TaskSessions to fetch.
   */
  where: Prisma.TaskSessionsWhereUniqueInput
}

/**
 * TaskSessions findUniqueOrThrow
 */
export type TaskSessionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * Filter, which TaskSessions to fetch.
   */
  where: Prisma.TaskSessionsWhereUniqueInput
}

/**
 * TaskSessions findFirst
 */
export type TaskSessionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * Filter, which TaskSessions to fetch.
   */
  where?: Prisma.TaskSessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskSessions to fetch.
   */
  orderBy?: Prisma.TaskSessionsOrderByWithRelationInput | Prisma.TaskSessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaskSessions.
   */
  cursor?: Prisma.TaskSessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskSessions.
   */
  distinct?: Prisma.TaskSessionsScalarFieldEnum | Prisma.TaskSessionsScalarFieldEnum[]
}

/**
 * TaskSessions findFirstOrThrow
 */
export type TaskSessionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * Filter, which TaskSessions to fetch.
   */
  where?: Prisma.TaskSessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskSessions to fetch.
   */
  orderBy?: Prisma.TaskSessionsOrderByWithRelationInput | Prisma.TaskSessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaskSessions.
   */
  cursor?: Prisma.TaskSessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskSessions.
   */
  distinct?: Prisma.TaskSessionsScalarFieldEnum | Prisma.TaskSessionsScalarFieldEnum[]
}

/**
 * TaskSessions findMany
 */
export type TaskSessionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * Filter, which TaskSessions to fetch.
   */
  where?: Prisma.TaskSessionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskSessions to fetch.
   */
  orderBy?: Prisma.TaskSessionsOrderByWithRelationInput | Prisma.TaskSessionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TaskSessions.
   */
  cursor?: Prisma.TaskSessionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskSessions.
   */
  distinct?: Prisma.TaskSessionsScalarFieldEnum | Prisma.TaskSessionsScalarFieldEnum[]
}

/**
 * TaskSessions create
 */
export type TaskSessionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * The data needed to create a TaskSessions.
   */
  data: Prisma.XOR<Prisma.TaskSessionsCreateInput, Prisma.TaskSessionsUncheckedCreateInput>
}

/**
 * TaskSessions createMany
 */
export type TaskSessionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TaskSessions.
   */
  data: Prisma.TaskSessionsCreateManyInput | Prisma.TaskSessionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TaskSessions createManyAndReturn
 */
export type TaskSessionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * The data used to create many TaskSessions.
   */
  data: Prisma.TaskSessionsCreateManyInput | Prisma.TaskSessionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TaskSessions update
 */
export type TaskSessionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * The data needed to update a TaskSessions.
   */
  data: Prisma.XOR<Prisma.TaskSessionsUpdateInput, Prisma.TaskSessionsUncheckedUpdateInput>
  /**
   * Choose, which TaskSessions to update.
   */
  where: Prisma.TaskSessionsWhereUniqueInput
}

/**
 * TaskSessions updateMany
 */
export type TaskSessionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TaskSessions.
   */
  data: Prisma.XOR<Prisma.TaskSessionsUpdateManyMutationInput, Prisma.TaskSessionsUncheckedUpdateManyInput>
  /**
   * Filter which TaskSessions to update
   */
  where?: Prisma.TaskSessionsWhereInput
  /**
   * Limit how many TaskSessions to update.
   */
  limit?: number
}

/**
 * TaskSessions updateManyAndReturn
 */
export type TaskSessionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * The data used to update TaskSessions.
   */
  data: Prisma.XOR<Prisma.TaskSessionsUpdateManyMutationInput, Prisma.TaskSessionsUncheckedUpdateManyInput>
  /**
   * Filter which TaskSessions to update
   */
  where?: Prisma.TaskSessionsWhereInput
  /**
   * Limit how many TaskSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TaskSessions upsert
 */
export type TaskSessionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * The filter to search for the TaskSessions to update in case it exists.
   */
  where: Prisma.TaskSessionsWhereUniqueInput
  /**
   * In case the TaskSessions found by the `where` argument doesn't exist, create a new TaskSessions with this data.
   */
  create: Prisma.XOR<Prisma.TaskSessionsCreateInput, Prisma.TaskSessionsUncheckedCreateInput>
  /**
   * In case the TaskSessions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaskSessionsUpdateInput, Prisma.TaskSessionsUncheckedUpdateInput>
}

/**
 * TaskSessions delete
 */
export type TaskSessionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
  /**
   * Filter which TaskSessions to delete.
   */
  where: Prisma.TaskSessionsWhereUniqueInput
}

/**
 * TaskSessions deleteMany
 */
export type TaskSessionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaskSessions to delete
   */
  where?: Prisma.TaskSessionsWhereInput
  /**
   * Limit how many TaskSessions to delete.
   */
  limit?: number
}

/**
 * TaskSessions without action
 */
export type TaskSessionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskSessions
   */
  select?: Prisma.TaskSessionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskSessions
   */
  omit?: Prisma.TaskSessionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskSessionsInclude<ExtArgs> | null
}
