
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TaskTypeProofType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TaskTypeProofType
 * 
 */
export type TaskTypeProofTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$TaskTypeProofTypePayload>

export type AggregateTaskTypeProofType = {
  _count: TaskTypeProofTypeCountAggregateOutputType | null
  _min: TaskTypeProofTypeMinAggregateOutputType | null
  _max: TaskTypeProofTypeMaxAggregateOutputType | null
}

export type TaskTypeProofTypeMinAggregateOutputType = {
  id: string | null
  taskTypeId: string | null
  proofTypeId: string | null
}

export type TaskTypeProofTypeMaxAggregateOutputType = {
  id: string | null
  taskTypeId: string | null
  proofTypeId: string | null
}

export type TaskTypeProofTypeCountAggregateOutputType = {
  id: number
  taskTypeId: number
  proofTypeId: number
  _all: number
}


export type TaskTypeProofTypeMinAggregateInputType = {
  id?: true
  taskTypeId?: true
  proofTypeId?: true
}

export type TaskTypeProofTypeMaxAggregateInputType = {
  id?: true
  taskTypeId?: true
  proofTypeId?: true
}

export type TaskTypeProofTypeCountAggregateInputType = {
  id?: true
  taskTypeId?: true
  proofTypeId?: true
  _all?: true
}

export type TaskTypeProofTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaskTypeProofType to aggregate.
   */
  where?: Prisma.TaskTypeProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskTypeProofTypes to fetch.
   */
  orderBy?: Prisma.TaskTypeProofTypeOrderByWithRelationInput | Prisma.TaskTypeProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaskTypeProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskTypeProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskTypeProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TaskTypeProofTypes
  **/
  _count?: true | TaskTypeProofTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaskTypeProofTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaskTypeProofTypeMaxAggregateInputType
}

export type GetTaskTypeProofTypeAggregateType<T extends TaskTypeProofTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateTaskTypeProofType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaskTypeProofType[P]>
    : Prisma.GetScalarType<T[P], AggregateTaskTypeProofType[P]>
}




export type TaskTypeProofTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskTypeProofTypeWhereInput
  orderBy?: Prisma.TaskTypeProofTypeOrderByWithAggregationInput | Prisma.TaskTypeProofTypeOrderByWithAggregationInput[]
  by: Prisma.TaskTypeProofTypeScalarFieldEnum[] | Prisma.TaskTypeProofTypeScalarFieldEnum
  having?: Prisma.TaskTypeProofTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaskTypeProofTypeCountAggregateInputType | true
  _min?: TaskTypeProofTypeMinAggregateInputType
  _max?: TaskTypeProofTypeMaxAggregateInputType
}

export type TaskTypeProofTypeGroupByOutputType = {
  id: string
  taskTypeId: string
  proofTypeId: string
  _count: TaskTypeProofTypeCountAggregateOutputType | null
  _min: TaskTypeProofTypeMinAggregateOutputType | null
  _max: TaskTypeProofTypeMaxAggregateOutputType | null
}

export type GetTaskTypeProofTypeGroupByPayload<T extends TaskTypeProofTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaskTypeProofTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaskTypeProofTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaskTypeProofTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaskTypeProofTypeGroupByOutputType[P]>
      }
    >
  >



export type TaskTypeProofTypeWhereInput = {
  AND?: Prisma.TaskTypeProofTypeWhereInput | Prisma.TaskTypeProofTypeWhereInput[]
  OR?: Prisma.TaskTypeProofTypeWhereInput[]
  NOT?: Prisma.TaskTypeProofTypeWhereInput | Prisma.TaskTypeProofTypeWhereInput[]
  id?: Prisma.StringFilter<"TaskTypeProofType"> | string
  taskTypeId?: Prisma.StringFilter<"TaskTypeProofType"> | string
  proofTypeId?: Prisma.StringFilter<"TaskTypeProofType"> | string
  taskType?: Prisma.XOR<Prisma.TaskTypeScalarRelationFilter, Prisma.TaskTypeWhereInput>
  proofType?: Prisma.XOR<Prisma.ProofTypeScalarRelationFilter, Prisma.ProofTypeWhereInput>
}

export type TaskTypeProofTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  taskTypeId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
  taskType?: Prisma.TaskTypeOrderByWithRelationInput
  proofType?: Prisma.ProofTypeOrderByWithRelationInput
}

export type TaskTypeProofTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TaskTypeProofTypeWhereInput | Prisma.TaskTypeProofTypeWhereInput[]
  OR?: Prisma.TaskTypeProofTypeWhereInput[]
  NOT?: Prisma.TaskTypeProofTypeWhereInput | Prisma.TaskTypeProofTypeWhereInput[]
  taskTypeId?: Prisma.StringFilter<"TaskTypeProofType"> | string
  proofTypeId?: Prisma.StringFilter<"TaskTypeProofType"> | string
  taskType?: Prisma.XOR<Prisma.TaskTypeScalarRelationFilter, Prisma.TaskTypeWhereInput>
  proofType?: Prisma.XOR<Prisma.ProofTypeScalarRelationFilter, Prisma.ProofTypeWhereInput>
}, "id">

export type TaskTypeProofTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  taskTypeId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
  _count?: Prisma.TaskTypeProofTypeCountOrderByAggregateInput
  _max?: Prisma.TaskTypeProofTypeMaxOrderByAggregateInput
  _min?: Prisma.TaskTypeProofTypeMinOrderByAggregateInput
}

export type TaskTypeProofTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaskTypeProofTypeScalarWhereWithAggregatesInput | Prisma.TaskTypeProofTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaskTypeProofTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaskTypeProofTypeScalarWhereWithAggregatesInput | Prisma.TaskTypeProofTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TaskTypeProofType"> | string
  taskTypeId?: Prisma.StringWithAggregatesFilter<"TaskTypeProofType"> | string
  proofTypeId?: Prisma.StringWithAggregatesFilter<"TaskTypeProofType"> | string
}

export type TaskTypeProofTypeCreateInput = {
  id?: string
  taskType: Prisma.TaskTypeCreateNestedOneWithoutRequiredProofTypesInput
  proofType: Prisma.ProofTypeCreateNestedOneWithoutTaskTypesInput
}

export type TaskTypeProofTypeUncheckedCreateInput = {
  id?: string
  taskTypeId: string
  proofTypeId: string
}

export type TaskTypeProofTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskType?: Prisma.TaskTypeUpdateOneRequiredWithoutRequiredProofTypesNestedInput
  proofType?: Prisma.ProofTypeUpdateOneRequiredWithoutTaskTypesNestedInput
}

export type TaskTypeProofTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TaskTypeProofTypeCreateManyInput = {
  id?: string
  taskTypeId: string
  proofTypeId: string
}

export type TaskTypeProofTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TaskTypeProofTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTypeId?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TaskTypeProofTypeListRelationFilter = {
  every?: Prisma.TaskTypeProofTypeWhereInput
  some?: Prisma.TaskTypeProofTypeWhereInput
  none?: Prisma.TaskTypeProofTypeWhereInput
}

export type TaskTypeProofTypeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TaskTypeProofTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskTypeId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
}

export type TaskTypeProofTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskTypeId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
}

export type TaskTypeProofTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskTypeId?: Prisma.SortOrder
  proofTypeId?: Prisma.SortOrder
}

export type TaskTypeProofTypeCreateNestedManyWithoutTaskTypeInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyTaskTypeInputEnvelope
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
}

export type TaskTypeProofTypeUncheckedCreateNestedManyWithoutTaskTypeInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyTaskTypeInputEnvelope
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
}

export type TaskTypeProofTypeUpdateManyWithoutTaskTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput[]
  upsert?: Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutTaskTypeInput | Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutTaskTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyTaskTypeInputEnvelope
  set?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  disconnect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  delete?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  update?: Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutTaskTypeInput | Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutTaskTypeInput[]
  updateMany?: Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutTaskTypeInput | Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutTaskTypeInput[]
  deleteMany?: Prisma.TaskTypeProofTypeScalarWhereInput | Prisma.TaskTypeProofTypeScalarWhereInput[]
}

export type TaskTypeProofTypeUncheckedUpdateManyWithoutTaskTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput[]
  upsert?: Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutTaskTypeInput | Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutTaskTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyTaskTypeInputEnvelope
  set?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  disconnect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  delete?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  update?: Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutTaskTypeInput | Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutTaskTypeInput[]
  updateMany?: Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutTaskTypeInput | Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutTaskTypeInput[]
  deleteMany?: Prisma.TaskTypeProofTypeScalarWhereInput | Prisma.TaskTypeProofTypeScalarWhereInput[]
}

export type TaskTypeProofTypeCreateNestedManyWithoutProofTypeInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyProofTypeInputEnvelope
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
}

export type TaskTypeProofTypeUncheckedCreateNestedManyWithoutProofTypeInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyProofTypeInputEnvelope
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
}

export type TaskTypeProofTypeUpdateManyWithoutProofTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput[]
  upsert?: Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutProofTypeInput | Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutProofTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyProofTypeInputEnvelope
  set?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  disconnect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  delete?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  update?: Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutProofTypeInput | Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutProofTypeInput[]
  updateMany?: Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutProofTypeInput | Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutProofTypeInput[]
  deleteMany?: Prisma.TaskTypeProofTypeScalarWhereInput | Prisma.TaskTypeProofTypeScalarWhereInput[]
}

export type TaskTypeProofTypeUncheckedUpdateManyWithoutProofTypeNestedInput = {
  create?: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput> | Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput[] | Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput[]
  connectOrCreate?: Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput | Prisma.TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput[]
  upsert?: Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutProofTypeInput | Prisma.TaskTypeProofTypeUpsertWithWhereUniqueWithoutProofTypeInput[]
  createMany?: Prisma.TaskTypeProofTypeCreateManyProofTypeInputEnvelope
  set?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  disconnect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  delete?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  connect?: Prisma.TaskTypeProofTypeWhereUniqueInput | Prisma.TaskTypeProofTypeWhereUniqueInput[]
  update?: Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutProofTypeInput | Prisma.TaskTypeProofTypeUpdateWithWhereUniqueWithoutProofTypeInput[]
  updateMany?: Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutProofTypeInput | Prisma.TaskTypeProofTypeUpdateManyWithWhereWithoutProofTypeInput[]
  deleteMany?: Prisma.TaskTypeProofTypeScalarWhereInput | Prisma.TaskTypeProofTypeScalarWhereInput[]
}

export type TaskTypeProofTypeCreateWithoutTaskTypeInput = {
  id?: string
  proofType: Prisma.ProofTypeCreateNestedOneWithoutTaskTypesInput
}

export type TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput = {
  id?: string
  proofTypeId: string
}

export type TaskTypeProofTypeCreateOrConnectWithoutTaskTypeInput = {
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput>
}

export type TaskTypeProofTypeCreateManyTaskTypeInputEnvelope = {
  data: Prisma.TaskTypeProofTypeCreateManyTaskTypeInput | Prisma.TaskTypeProofTypeCreateManyTaskTypeInput[]
  skipDuplicates?: boolean
}

export type TaskTypeProofTypeUpsertWithWhereUniqueWithoutTaskTypeInput = {
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
  update: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedUpdateWithoutTaskTypeInput>
  create: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutTaskTypeInput>
}

export type TaskTypeProofTypeUpdateWithWhereUniqueWithoutTaskTypeInput = {
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
  data: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateWithoutTaskTypeInput, Prisma.TaskTypeProofTypeUncheckedUpdateWithoutTaskTypeInput>
}

export type TaskTypeProofTypeUpdateManyWithWhereWithoutTaskTypeInput = {
  where: Prisma.TaskTypeProofTypeScalarWhereInput
  data: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateManyMutationInput, Prisma.TaskTypeProofTypeUncheckedUpdateManyWithoutTaskTypeInput>
}

export type TaskTypeProofTypeScalarWhereInput = {
  AND?: Prisma.TaskTypeProofTypeScalarWhereInput | Prisma.TaskTypeProofTypeScalarWhereInput[]
  OR?: Prisma.TaskTypeProofTypeScalarWhereInput[]
  NOT?: Prisma.TaskTypeProofTypeScalarWhereInput | Prisma.TaskTypeProofTypeScalarWhereInput[]
  id?: Prisma.StringFilter<"TaskTypeProofType"> | string
  taskTypeId?: Prisma.StringFilter<"TaskTypeProofType"> | string
  proofTypeId?: Prisma.StringFilter<"TaskTypeProofType"> | string
}

export type TaskTypeProofTypeCreateWithoutProofTypeInput = {
  id?: string
  taskType: Prisma.TaskTypeCreateNestedOneWithoutRequiredProofTypesInput
}

export type TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput = {
  id?: string
  taskTypeId: string
}

export type TaskTypeProofTypeCreateOrConnectWithoutProofTypeInput = {
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput>
}

export type TaskTypeProofTypeCreateManyProofTypeInputEnvelope = {
  data: Prisma.TaskTypeProofTypeCreateManyProofTypeInput | Prisma.TaskTypeProofTypeCreateManyProofTypeInput[]
  skipDuplicates?: boolean
}

export type TaskTypeProofTypeUpsertWithWhereUniqueWithoutProofTypeInput = {
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
  update: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedUpdateWithoutProofTypeInput>
  create: Prisma.XOR<Prisma.TaskTypeProofTypeCreateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedCreateWithoutProofTypeInput>
}

export type TaskTypeProofTypeUpdateWithWhereUniqueWithoutProofTypeInput = {
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
  data: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateWithoutProofTypeInput, Prisma.TaskTypeProofTypeUncheckedUpdateWithoutProofTypeInput>
}

export type TaskTypeProofTypeUpdateManyWithWhereWithoutProofTypeInput = {
  where: Prisma.TaskTypeProofTypeScalarWhereInput
  data: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateManyMutationInput, Prisma.TaskTypeProofTypeUncheckedUpdateManyWithoutProofTypeInput>
}

export type TaskTypeProofTypeCreateManyTaskTypeInput = {
  id?: string
  proofTypeId: string
}

export type TaskTypeProofTypeUpdateWithoutTaskTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofType?: Prisma.ProofTypeUpdateOneRequiredWithoutTaskTypesNestedInput
}

export type TaskTypeProofTypeUncheckedUpdateWithoutTaskTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TaskTypeProofTypeUncheckedUpdateManyWithoutTaskTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  proofTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TaskTypeProofTypeCreateManyProofTypeInput = {
  id?: string
  taskTypeId: string
}

export type TaskTypeProofTypeUpdateWithoutProofTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskType?: Prisma.TaskTypeUpdateOneRequiredWithoutRequiredProofTypesNestedInput
}

export type TaskTypeProofTypeUncheckedUpdateWithoutProofTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TaskTypeProofTypeUncheckedUpdateManyWithoutProofTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskTypeId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TaskTypeProofTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskTypeId?: boolean
  proofTypeId?: boolean
  taskType?: boolean | Prisma.TaskTypeDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskTypeProofType"]>

export type TaskTypeProofTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskTypeId?: boolean
  proofTypeId?: boolean
  taskType?: boolean | Prisma.TaskTypeDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskTypeProofType"]>

export type TaskTypeProofTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  taskTypeId?: boolean
  proofTypeId?: boolean
  taskType?: boolean | Prisma.TaskTypeDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taskTypeProofType"]>

export type TaskTypeProofTypeSelectScalar = {
  id?: boolean
  taskTypeId?: boolean
  proofTypeId?: boolean
}

export type TaskTypeProofTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "taskTypeId" | "proofTypeId", ExtArgs["result"]["taskTypeProofType"]>
export type TaskTypeProofTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taskType?: boolean | Prisma.TaskTypeDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}
export type TaskTypeProofTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taskType?: boolean | Prisma.TaskTypeDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}
export type TaskTypeProofTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  taskType?: boolean | Prisma.TaskTypeDefaultArgs<ExtArgs>
  proofType?: boolean | Prisma.ProofTypeDefaultArgs<ExtArgs>
}

export type $TaskTypeProofTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TaskTypeProofType"
  objects: {
    taskType: Prisma.$TaskTypePayload<ExtArgs>
    proofType: Prisma.$ProofTypePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    taskTypeId: string
    proofTypeId: string
  }, ExtArgs["result"]["taskTypeProofType"]>
  composites: {}
}

export type TaskTypeProofTypeGetPayload<S extends boolean | null | undefined | TaskTypeProofTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload, S>

export type TaskTypeProofTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaskTypeProofTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TaskTypeProofTypeCountAggregateInputType | true
  }

export interface TaskTypeProofTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TaskTypeProofType'], meta: { name: 'TaskTypeProofType' } }
  /**
   * Find zero or one TaskTypeProofType that matches the filter.
   * @param {TaskTypeProofTypeFindUniqueArgs} args - Arguments to find a TaskTypeProofType
   * @example
   * // Get one TaskTypeProofType
   * const taskTypeProofType = await prisma.taskTypeProofType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaskTypeProofTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TaskTypeProofType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaskTypeProofTypeFindUniqueOrThrowArgs} args - Arguments to find a TaskTypeProofType
   * @example
   * // Get one TaskTypeProofType
   * const taskTypeProofType = await prisma.taskTypeProofType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaskTypeProofTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaskTypeProofType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskTypeProofTypeFindFirstArgs} args - Arguments to find a TaskTypeProofType
   * @example
   * // Get one TaskTypeProofType
   * const taskTypeProofType = await prisma.taskTypeProofType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaskTypeProofTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, TaskTypeProofTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TaskTypeProofType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskTypeProofTypeFindFirstOrThrowArgs} args - Arguments to find a TaskTypeProofType
   * @example
   * // Get one TaskTypeProofType
   * const taskTypeProofType = await prisma.taskTypeProofType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaskTypeProofTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaskTypeProofTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TaskTypeProofTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskTypeProofTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TaskTypeProofTypes
   * const taskTypeProofTypes = await prisma.taskTypeProofType.findMany()
   * 
   * // Get first 10 TaskTypeProofTypes
   * const taskTypeProofTypes = await prisma.taskTypeProofType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taskTypeProofTypeWithIdOnly = await prisma.taskTypeProofType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaskTypeProofTypeFindManyArgs>(args?: Prisma.SelectSubset<T, TaskTypeProofTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TaskTypeProofType.
   * @param {TaskTypeProofTypeCreateArgs} args - Arguments to create a TaskTypeProofType.
   * @example
   * // Create one TaskTypeProofType
   * const TaskTypeProofType = await prisma.taskTypeProofType.create({
   *   data: {
   *     // ... data to create a TaskTypeProofType
   *   }
   * })
   * 
   */
  create<T extends TaskTypeProofTypeCreateArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeCreateArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TaskTypeProofTypes.
   * @param {TaskTypeProofTypeCreateManyArgs} args - Arguments to create many TaskTypeProofTypes.
   * @example
   * // Create many TaskTypeProofTypes
   * const taskTypeProofType = await prisma.taskTypeProofType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaskTypeProofTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, TaskTypeProofTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TaskTypeProofTypes and returns the data saved in the database.
   * @param {TaskTypeProofTypeCreateManyAndReturnArgs} args - Arguments to create many TaskTypeProofTypes.
   * @example
   * // Create many TaskTypeProofTypes
   * const taskTypeProofType = await prisma.taskTypeProofType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TaskTypeProofTypes and only return the `id`
   * const taskTypeProofTypeWithIdOnly = await prisma.taskTypeProofType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaskTypeProofTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaskTypeProofTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TaskTypeProofType.
   * @param {TaskTypeProofTypeDeleteArgs} args - Arguments to delete one TaskTypeProofType.
   * @example
   * // Delete one TaskTypeProofType
   * const TaskTypeProofType = await prisma.taskTypeProofType.delete({
   *   where: {
   *     // ... filter to delete one TaskTypeProofType
   *   }
   * })
   * 
   */
  delete<T extends TaskTypeProofTypeDeleteArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TaskTypeProofType.
   * @param {TaskTypeProofTypeUpdateArgs} args - Arguments to update one TaskTypeProofType.
   * @example
   * // Update one TaskTypeProofType
   * const taskTypeProofType = await prisma.taskTypeProofType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaskTypeProofTypeUpdateArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TaskTypeProofTypes.
   * @param {TaskTypeProofTypeDeleteManyArgs} args - Arguments to filter TaskTypeProofTypes to delete.
   * @example
   * // Delete a few TaskTypeProofTypes
   * const { count } = await prisma.taskTypeProofType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaskTypeProofTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaskTypeProofTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaskTypeProofTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskTypeProofTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TaskTypeProofTypes
   * const taskTypeProofType = await prisma.taskTypeProofType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaskTypeProofTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TaskTypeProofTypes and returns the data updated in the database.
   * @param {TaskTypeProofTypeUpdateManyAndReturnArgs} args - Arguments to update many TaskTypeProofTypes.
   * @example
   * // Update many TaskTypeProofTypes
   * const taskTypeProofType = await prisma.taskTypeProofType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TaskTypeProofTypes and only return the `id`
   * const taskTypeProofTypeWithIdOnly = await prisma.taskTypeProofType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaskTypeProofTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TaskTypeProofType.
   * @param {TaskTypeProofTypeUpsertArgs} args - Arguments to update or create a TaskTypeProofType.
   * @example
   * // Update or create a TaskTypeProofType
   * const taskTypeProofType = await prisma.taskTypeProofType.upsert({
   *   create: {
   *     // ... data to create a TaskTypeProofType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TaskTypeProofType we want to update
   *   }
   * })
   */
  upsert<T extends TaskTypeProofTypeUpsertArgs>(args: Prisma.SelectSubset<T, TaskTypeProofTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__TaskTypeProofTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypeProofTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TaskTypeProofTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskTypeProofTypeCountArgs} args - Arguments to filter TaskTypeProofTypes to count.
   * @example
   * // Count the number of TaskTypeProofTypes
   * const count = await prisma.taskTypeProofType.count({
   *   where: {
   *     // ... the filter for the TaskTypeProofTypes we want to count
   *   }
   * })
  **/
  count<T extends TaskTypeProofTypeCountArgs>(
    args?: Prisma.Subset<T, TaskTypeProofTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaskTypeProofTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TaskTypeProofType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskTypeProofTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaskTypeProofTypeAggregateArgs>(args: Prisma.Subset<T, TaskTypeProofTypeAggregateArgs>): Prisma.PrismaPromise<GetTaskTypeProofTypeAggregateType<T>>

  /**
   * Group by TaskTypeProofType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskTypeProofTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaskTypeProofTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaskTypeProofTypeGroupByArgs['orderBy'] }
      : { orderBy?: TaskTypeProofTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaskTypeProofTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaskTypeProofTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TaskTypeProofType model
 */
readonly fields: TaskTypeProofTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TaskTypeProofType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaskTypeProofTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  taskType<T extends Prisma.TaskTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskTypeClient<runtime.Types.Result.GetResult<Prisma.$TaskTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  proofType<T extends Prisma.ProofTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProofTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__ProofTypeClient<runtime.Types.Result.GetResult<Prisma.$ProofTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TaskTypeProofType model
 */
export interface TaskTypeProofTypeFieldRefs {
  readonly id: Prisma.FieldRef<"TaskTypeProofType", 'String'>
  readonly taskTypeId: Prisma.FieldRef<"TaskTypeProofType", 'String'>
  readonly proofTypeId: Prisma.FieldRef<"TaskTypeProofType", 'String'>
}
    

// Custom InputTypes
/**
 * TaskTypeProofType findUnique
 */
export type TaskTypeProofTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which TaskTypeProofType to fetch.
   */
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
}

/**
 * TaskTypeProofType findUniqueOrThrow
 */
export type TaskTypeProofTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which TaskTypeProofType to fetch.
   */
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
}

/**
 * TaskTypeProofType findFirst
 */
export type TaskTypeProofTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which TaskTypeProofType to fetch.
   */
  where?: Prisma.TaskTypeProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskTypeProofTypes to fetch.
   */
  orderBy?: Prisma.TaskTypeProofTypeOrderByWithRelationInput | Prisma.TaskTypeProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaskTypeProofTypes.
   */
  cursor?: Prisma.TaskTypeProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskTypeProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskTypeProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskTypeProofTypes.
   */
  distinct?: Prisma.TaskTypeProofTypeScalarFieldEnum | Prisma.TaskTypeProofTypeScalarFieldEnum[]
}

/**
 * TaskTypeProofType findFirstOrThrow
 */
export type TaskTypeProofTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which TaskTypeProofType to fetch.
   */
  where?: Prisma.TaskTypeProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskTypeProofTypes to fetch.
   */
  orderBy?: Prisma.TaskTypeProofTypeOrderByWithRelationInput | Prisma.TaskTypeProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TaskTypeProofTypes.
   */
  cursor?: Prisma.TaskTypeProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskTypeProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskTypeProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskTypeProofTypes.
   */
  distinct?: Prisma.TaskTypeProofTypeScalarFieldEnum | Prisma.TaskTypeProofTypeScalarFieldEnum[]
}

/**
 * TaskTypeProofType findMany
 */
export type TaskTypeProofTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * Filter, which TaskTypeProofTypes to fetch.
   */
  where?: Prisma.TaskTypeProofTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TaskTypeProofTypes to fetch.
   */
  orderBy?: Prisma.TaskTypeProofTypeOrderByWithRelationInput | Prisma.TaskTypeProofTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TaskTypeProofTypes.
   */
  cursor?: Prisma.TaskTypeProofTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TaskTypeProofTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TaskTypeProofTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TaskTypeProofTypes.
   */
  distinct?: Prisma.TaskTypeProofTypeScalarFieldEnum | Prisma.TaskTypeProofTypeScalarFieldEnum[]
}

/**
 * TaskTypeProofType create
 */
export type TaskTypeProofTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a TaskTypeProofType.
   */
  data: Prisma.XOR<Prisma.TaskTypeProofTypeCreateInput, Prisma.TaskTypeProofTypeUncheckedCreateInput>
}

/**
 * TaskTypeProofType createMany
 */
export type TaskTypeProofTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TaskTypeProofTypes.
   */
  data: Prisma.TaskTypeProofTypeCreateManyInput | Prisma.TaskTypeProofTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TaskTypeProofType createManyAndReturn
 */
export type TaskTypeProofTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * The data used to create many TaskTypeProofTypes.
   */
  data: Prisma.TaskTypeProofTypeCreateManyInput | Prisma.TaskTypeProofTypeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TaskTypeProofType update
 */
export type TaskTypeProofTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a TaskTypeProofType.
   */
  data: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateInput, Prisma.TaskTypeProofTypeUncheckedUpdateInput>
  /**
   * Choose, which TaskTypeProofType to update.
   */
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
}

/**
 * TaskTypeProofType updateMany
 */
export type TaskTypeProofTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TaskTypeProofTypes.
   */
  data: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateManyMutationInput, Prisma.TaskTypeProofTypeUncheckedUpdateManyInput>
  /**
   * Filter which TaskTypeProofTypes to update
   */
  where?: Prisma.TaskTypeProofTypeWhereInput
  /**
   * Limit how many TaskTypeProofTypes to update.
   */
  limit?: number
}

/**
 * TaskTypeProofType updateManyAndReturn
 */
export type TaskTypeProofTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * The data used to update TaskTypeProofTypes.
   */
  data: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateManyMutationInput, Prisma.TaskTypeProofTypeUncheckedUpdateManyInput>
  /**
   * Filter which TaskTypeProofTypes to update
   */
  where?: Prisma.TaskTypeProofTypeWhereInput
  /**
   * Limit how many TaskTypeProofTypes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TaskTypeProofType upsert
 */
export type TaskTypeProofTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the TaskTypeProofType to update in case it exists.
   */
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
  /**
   * In case the TaskTypeProofType found by the `where` argument doesn't exist, create a new TaskTypeProofType with this data.
   */
  create: Prisma.XOR<Prisma.TaskTypeProofTypeCreateInput, Prisma.TaskTypeProofTypeUncheckedCreateInput>
  /**
   * In case the TaskTypeProofType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaskTypeProofTypeUpdateInput, Prisma.TaskTypeProofTypeUncheckedUpdateInput>
}

/**
 * TaskTypeProofType delete
 */
export type TaskTypeProofTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
  /**
   * Filter which TaskTypeProofType to delete.
   */
  where: Prisma.TaskTypeProofTypeWhereUniqueInput
}

/**
 * TaskTypeProofType deleteMany
 */
export type TaskTypeProofTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TaskTypeProofTypes to delete
   */
  where?: Prisma.TaskTypeProofTypeWhereInput
  /**
   * Limit how many TaskTypeProofTypes to delete.
   */
  limit?: number
}

/**
 * TaskTypeProofType without action
 */
export type TaskTypeProofTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskTypeProofType
   */
  select?: Prisma.TaskTypeProofTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskTypeProofType
   */
  omit?: Prisma.TaskTypeProofTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskTypeProofTypeInclude<ExtArgs> | null
}
